var db = require('../lib/mongo').db;

var mlb_players = [
	{'first_name': 'Albert', 'last_name': 'Pujols', 'rank': 1, 'team': 'StL', 'active': 1, 'position': ['1B']},
	{'first_name': 'Miguel', 'last_name': 'Cabrera', 'rank': 2, 'team': 'Det', 'active': 1, 'position': ['1B']},
	{'first_name': 'Hanley', 'last_name': 'Ramirez', 'rank': 3, 'team': 'Fla', 'active': 1, 'position': ['SS']},
	{'first_name': 'Carl', 'last_name': 'Crawford', 'rank': 4, 'team': 'Bos', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Evan', 'last_name': 'Longoria', 'rank': 5, 'team': 'TB', 'active': 1, 'position': ['3B']},
	{'first_name': 'Ryan', 'last_name': 'Braun', 'rank': 6, 'team': 'Mil', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Robinson', 'last_name': 'Cano', 'rank': 7, 'team': 'NYY', 'active': 1, 'position': ['2B']},
	{'first_name': 'Joey', 'last_name': 'Votto', 'rank': 8, 'team': 'Cin', 'active': 1, 'position': ['1B']},
	{'first_name': 'Carlos', 'last_name': 'Gonzalez', 'rank': 9, 'team': 'Col', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'David', 'last_name': 'Wright', 'rank': 10, 'team': 'NYM', 'active': 1, 'position': ['3B']},
	{'first_name': 'Troy', 'last_name': 'Tulowitzki', 'rank': 11, 'team': 'Col', 'active': 1, 'position': ['SS']},
	{'first_name': 'Adrian', 'last_name': 'Gonzalez', 'rank': 12, 'team': 'Bos', 'active': 1, 'position': ['1B']},
	{'first_name': 'Matt', 'last_name': 'Holliday', 'rank': 13, 'team': 'StL', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Chase', 'last_name': 'Utley', 'rank': 14, 'team': 'Phi', 'active': 1, 'position': ['2B']},
	{'first_name': 'Josh', 'last_name': 'Hamilton', 'rank': 15, 'team': 'Tex', 'active': 1, 'position': ['LF', 'CF', 'OF']},
	{'first_name': 'Ryan', 'last_name': 'Zimmerman', 'rank': 16, 'team': 'Was', 'active': 1, 'position': ['3B']},
	{'first_name': 'Kevin', 'last_name': 'Youkilis', 'rank': 17, 'team': 'Bos', 'active': 1, 'position': ['1B']},
	{'first_name': 'Matt', 'last_name': 'Kemp', 'rank': 18, 'team': 'LAD', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Mark', 'last_name': 'Teixeira', 'rank': 19, 'team': 'NYY', 'active': 1, 'position': ['1B']},
	{'first_name': 'Alex', 'last_name': 'Rodriguez', 'rank': 20, 'team': 'NYY', 'active': 1, 'position': ['3B']},
	{'first_name': 'Nelson', 'last_name': 'Cruz', 'rank': 21, 'team': 'Tex', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Prince', 'last_name': 'Fielder', 'rank': 22, 'team': 'Mil', 'active': 1, 'position': ['1B']},
	{'first_name': 'Dustin', 'last_name': 'Pedroia', 'rank': 23, 'team': 'Bos', 'active': 1, 'position': ['2B']},
	{'first_name': 'Shin-Soo', 'last_name': 'Choo', 'rank': 24, 'team': 'Cle', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Ryan', 'last_name': 'Howard', 'rank': 25, 'team': 'Phi', 'active': 1, 'position': ['1B']},
	{'first_name': 'Joe', 'last_name': 'Mauer', 'rank': 26, 'team': 'Min', 'active': 1, 'position': ['C', 'DH']},
	{'first_name': 'Justin', 'last_name': 'Upton', 'rank': 27, 'team': 'Ari', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Andrew', 'last_name': 'McCutchen', 'rank': 28, 'team': 'Pit', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Adrian', 'last_name': 'Beltre', 'rank': 29, 'team': 'Tex', 'active': 1, 'position': ['3B']},
	{'first_name': 'Jose', 'last_name': 'Reyes', 'rank': 30, 'team': 'NYM', 'active': 1, 'position': ['SS']},
	{'first_name': 'Jose', 'last_name': 'Bautista', 'rank': 31, 'team': 'Tor', 'active': 1, 'position': ['3B', 'RF', 'OF']},
	{'first_name': 'Adam', 'last_name': 'Dunn', 'rank': 32, 'team': 'CWS', 'active': 1, 'position': ['1B']},
	{'first_name': 'Dan', 'last_name': 'Uggla', 'rank': 33, 'team': 'Atl', 'active': 1, 'position': ['2B']},
	{'first_name': 'Jayson', 'last_name': 'Werth', 'rank': 34, 'team': 'Was', 'active': 1, 'position': ['CF', 'RF', 'OF']},
	{'first_name': 'Ichiro', 'last_name': 'Suzuki', 'rank': 35, 'team': 'Sea', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Jason', 'last_name': 'Heyward', 'rank': 36, 'team': 'Atl', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Victor', 'last_name': 'Martinez', 'rank': 37, 'team': 'Det', 'active': 1, 'position': ['C']},
	{'first_name': 'Ian', 'last_name': 'Kinsler', 'rank': 38, 'team': 'Tex', 'active': 1, 'position': ['2B']},
	{'first_name': 'Alex', 'last_name': 'Rios', 'rank': 39, 'team': 'CWS', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Hunter', 'last_name': 'Pence', 'rank': 40, 'team': 'Hou', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Brian', 'last_name': 'McCann', 'rank': 41, 'team': 'Atl', 'active': 1, 'position': ['C']},
	{'first_name': 'Brandon', 'last_name': 'Phillips', 'rank': 42, 'team': 'Cin', 'active': 1, 'position': ['2B']},
	{'first_name': 'Jacoby', 'last_name': 'Ellsbury', 'rank': 43, 'team': 'Bos', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Buster', 'last_name': 'Posey', 'rank': 44, 'team': 'SF', 'active': 1, 'position': ['C', '1B']},
	{'first_name': 'Michael', 'last_name': 'Young', 'rank': 45, 'team': 'Tex', 'active': 1, 'position': ['3B']},
	{'first_name': 'Derek', 'last_name': 'Jeter', 'rank': 46, 'team': 'NYY', 'active': 1, 'position': ['SS']},
	{'first_name': 'Andre', 'last_name': 'Ethier', 'rank': 47, 'team': 'LAD', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Rickie', 'last_name': 'Weeks', 'rank': 48, 'team': 'Mil', 'active': 1, 'position': ['2B']},
	{'first_name': 'Jimmy', 'last_name': 'Rollins', 'rank': 49, 'team': 'Phi', 'active': 1, 'position': ['SS']},
	{'first_name': 'Justin', 'last_name': 'Morneau', 'rank': 50, 'team': 'Min', 'active': 1, 'position': ['1B']},
	{'first_name': 'Aramis', 'last_name': 'Ramirez', 'rank': 51, 'team': 'ChC', 'active': 1, 'position': ['3B']},
	{'first_name': 'B.J.', 'last_name': 'Upton', 'rank': 52, 'team': 'TB', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Mike', 'last_name': 'Stanton', 'rank': 53, 'team': 'Fla', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Kendry', 'last_name': 'Morales', 'rank': 54, 'team': 'LAA', 'active': 1, 'position': ['1B']},
	{'first_name': 'Shane', 'last_name': 'Victorino', 'rank': 55, 'team': 'Phi', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Jay', 'last_name': 'Bruce', 'rank': 56, 'team': 'Cin', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Chris', 'last_name': 'Young', 'rank': 57, 'team': 'Ari', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Martin', 'last_name': 'Prado', 'rank': 58, 'team': 'Atl', 'active': 1, 'position': ['2B', '3B']},
	{'first_name': 'Elvis', 'last_name': 'Andrus', 'rank': 59, 'team': 'Tex', 'active': 1, 'position': ['SS']},
	{'first_name': 'Corey', 'last_name': 'Hart', 'rank': 60, 'team': 'Mil', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Paul', 'last_name': 'Konerko', 'rank': 61, 'team': 'CWS', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Delmon', 'last_name': 'Young', 'rank': 62, 'team': 'Min', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Billy', 'last_name': 'Butler', 'rank': 63, 'team': 'KC', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Michael', 'last_name': 'Bourn', 'rank': 64, 'team': 'Hou', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Carlos', 'last_name': 'Santana', 'rank': 65, 'team': 'Cle', 'active': 1, 'position': ['C']},
	{'first_name': 'Alexei', 'last_name': 'Ramirez', 'rank': 66, 'team': 'CWS', 'active': 1, 'position': ['SS']},
	{'first_name': 'Curtis', 'last_name': 'Granderson', 'rank': 67, 'team': 'NYY', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Colby', 'last_name': 'Rasmus', 'rank': 68, 'team': 'StL', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Ben', 'last_name': 'Zobrist', 'rank': 69, 'team': 'TB', 'active': 1, 'position': ['2B', 'RF', 'OF']},
	{'first_name': 'Casey', 'last_name': 'McGehee', 'rank': 70, 'team': 'Mil', 'active': 1, 'position': ['3B']},
	{'first_name': 'Drew', 'last_name': 'Stubbs', 'rank': 71, 'team': 'Cin', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Kelly', 'last_name': 'Johnson', 'rank': 72, 'team': 'Ari', 'active': 1, 'position': ['2B']},
	{'first_name': 'Brett', 'last_name': 'Gardner', 'rank': 73, 'team': 'NYY', 'active': 1, 'position': ['LF', 'CF', 'OF']},
	{'first_name': 'Aaron', 'last_name': 'Hill', 'rank': 74, 'team': 'Tor', 'active': 1, 'position': ['2B']},
	{'first_name': 'Stephen', 'last_name': 'Drew', 'rank': 75, 'team': 'Ari', 'active': 1, 'position': ['SS']},
	{'first_name': 'Torii', 'last_name': 'Hunter', 'rank': 76, 'team': 'LAA', 'active': 1, 'position': ['CF', 'RF', 'OF']},
	{'first_name': 'Juan', 'last_name': 'Pierre', 'rank': 77, 'team': 'CWS', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Adam', 'last_name': 'Lind', 'rank': 78, 'team': 'Tor', 'active': 1, 'position': ['LF', 'OF', 'DH']},
	{'first_name': 'Aubrey', 'last_name': 'Huff', 'rank': 79, 'team': 'SF', 'active': 1, 'position': ['1B', 'LF', 'RF', 'OF']},
	{'first_name': 'Carlos', 'last_name': 'Quentin', 'rank': 80, 'team': 'CWS', 'active': 1, 'position': ['RF', 'OF', 'DH']},
	{'first_name': 'Pablo', 'last_name': 'Sandoval', 'rank': 81, 'team': 'SF', 'active': 1, 'position': ['3B']},
	{'first_name': 'Gordon', 'last_name': 'Beckham', 'rank': 82, 'team': 'CWS', 'active': 1, 'position': ['2B']},
	{'first_name': 'David', 'last_name': 'Ortiz', 'rank': 83, 'team': 'Bos', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Bobby', 'last_name': 'Abreu', 'rank': 84, 'team': 'LAA', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Vernon', 'last_name': 'Wells', 'rank': 85, 'team': 'LAA', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Adam', 'last_name': 'Jones', 'rank': 86, 'team': 'Bal', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Pedro', 'last_name': 'Alvarez', 'rank': 87, 'team': 'Pit', 'active': 1, 'position': ['3B']},
	{'first_name': 'Chone', 'last_name': 'Figgins', 'rank': 88, 'team': 'Sea', 'active': 1, 'position': ['2B']},
	{'first_name': 'Adam', 'last_name': 'LaRoche', 'rank': 89, 'team': 'Was', 'active': 1, 'position': ['1B']},
	{'first_name': 'Geovany', 'last_name': 'Soto', 'rank': 90, 'team': 'ChC', 'active': 1, 'position': ['C']},
	{'first_name': 'Angel', 'last_name': 'Pagan', 'rank': 91, 'team': 'NYM', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'Ian', 'last_name': 'Desmond', 'rank': 92, 'team': 'Was', 'active': 1, 'position': ['SS']},
	{'first_name': 'Rajai', 'last_name': 'Davis', 'rank': 93, 'team': 'Tor', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'Howard', 'last_name': 'Kendrick', 'rank': 94, 'team': 'LAA', 'active': 1, 'position': ['2B']},
	{'first_name': 'Nick', 'last_name': 'Markakis', 'rank': 95, 'team': 'Bal', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Rafael', 'last_name': 'Furcal', 'rank': 96, 'team': 'LAD', 'active': 1, 'position': ['SS']},
	{'first_name': 'Carlos', 'last_name': 'Lee', 'rank': 97, 'team': 'Hou', 'active': 1, 'position': ['OF', '1B']},
	{'first_name': 'Miguel', 'last_name': 'Montero', 'rank': 98, 'team': 'Ari', 'active': 1, 'position': ['C']},
	{'first_name': 'Brian', 'last_name': 'Roberts', 'rank': 99, 'team': 'Bal', 'active': 1, 'position': ['2B']},
	{'first_name': 'Ian', 'last_name': 'Stewart', 'rank': 100, 'team': 'Col', 'active': 1, 'position': ['3B']},
	{'first_name': 'Vladimir', 'last_name': 'Guerrero', 'rank': 101, 'team': 'Bal', 'active': 1, 'position': ['RF', 'OF', 'DH']},
	{'first_name': 'Carlos', 'last_name': 'Pena', 'rank': 102, 'team': 'ChC', 'active': 1, 'position': ['1B']},
	{'first_name': 'Derrek', 'last_name': 'Lee', 'rank': 103, 'team': 'Bal', 'active': 1, 'position': ['1B']},
	{'first_name': 'Starlin', 'last_name': 'Castro', 'rank': 104, 'team': 'ChC', 'active': 1, 'position': ['SS']},
	{'first_name': 'Mark', 'last_name': 'Reynolds', 'rank': 105, 'team': 'Bal', 'active': 1, 'position': ['3B']},
	{'first_name': 'Grady', 'last_name': 'Sizemore', 'rank': 106, 'team': 'Cle', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Neil', 'last_name': 'Walker', 'rank': 107, 'team': 'Pit', 'active': 1, 'position': ['2B']},
	{'first_name': 'Gaby', 'last_name': 'Sanchez', 'rank': 108, 'team': 'Fla', 'active': 1, 'position': ['1B']},
	{'first_name': 'Mike', 'last_name': 'Napoli', 'rank': 109, 'team': 'Tex', 'active': 1, 'position': ['C', '1B']},
	{'first_name': 'Placido', 'last_name': 'Polanco', 'rank': 110, 'team': 'Phi', 'active': 1, 'position': ['3B']},
	{'first_name': 'Nick', 'last_name': 'Swisher', 'rank': 111, 'team': 'NYY', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Erick', 'last_name': 'Aybar', 'rank': 112, 'team': 'LAA', 'active': 1, 'position': ['SS']},
	{'first_name': 'Mitch', 'last_name': 'Moreland', 'rank': 113, 'team': 'Tex', 'active': 1, 'position': ['1B']},
	{'first_name': 'Jason', 'last_name': 'Bay', 'rank': 114, 'team': 'NYM', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Sean', 'last_name': 'Rodriguez', 'rank': 115, 'team': 'TB', 'active': 1, 'position': ['2B', 'CF', 'OF']},
	{'first_name': 'Travis', 'last_name': 'Snider', 'rank': 116, 'team': 'Tor', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Alcides', 'last_name': 'Escobar', 'rank': 117, 'team': 'KC', 'active': 1, 'position': ['SS']},
	{'first_name': 'Michael', 'last_name': 'Cuddyer', 'rank': 118, 'team': 'Min', 'active': 1, 'position': ['RF', 'OF', '1B']},
	{'first_name': 'Carlos', 'last_name': 'Beltran', 'rank': 119, 'team': 'NYM', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Lance', 'last_name': 'Berkman', 'rank': 120, 'team': 'StL', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Chase', 'last_name': 'Headley', 'rank': 121, 'team': 'SD', 'active': 1, 'position': ['3B']},
	{'first_name': 'Luke', 'last_name': 'Scott', 'rank': 122, 'team': 'Bal', 'active': 1, 'position': ['LF', 'OF', '1B', 'DH']},
	{'first_name': 'Andres', 'last_name': 'Torres', 'rank': 123, 'team': 'SF', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'Matt', 'last_name': 'Wieters', 'rank': 124, 'team': 'Bal', 'active': 1, 'position': ['C']},
	{'first_name': 'Denard', 'last_name': 'Span', 'rank': 125, 'team': 'Min', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Tsuyoshi', 'last_name': 'Nishioka', 'rank': 126, 'team': 'Min', 'active': 1, 'position': ['2B']},
	{'first_name': 'Manny', 'last_name': 'Ramirez', 'rank': 127, 'team': 'TB', 'active': 1, 'position': ['LF', 'OF', 'DH']},
	{'first_name': 'Edwin', 'last_name': 'Encarnacion', 'rank': 128, 'team': 'Tor', 'active': 1, 'position': ['3B']},
	{'first_name': 'Ike', 'last_name': 'Davis', 'rank': 129, 'team': 'NYM', 'active': 1, 'position': ['1B']},
	{'first_name': 'Jose', 'last_name': 'Lopez', 'rank': 130, 'team': 'Col', 'active': 1, 'position': ['3B']},
	{'first_name': 'James', 'last_name': 'Loney', 'rank': 131, 'team': 'LAD', 'active': 1, 'position': ['1B']},
	{'first_name': 'Asdrubal', 'last_name': 'Cabrera', 'rank': 132, 'team': 'Cle', 'active': 1, 'position': ['SS']},
	{'first_name': 'David', 'last_name': 'Freese', 'rank': 133, 'team': 'StL', 'active': 1, 'position': ['3B']},
	{'first_name': 'Yunel', 'last_name': 'Escobar', 'rank': 134, 'team': 'Tor', 'active': 1, 'position': ['SS']},
	{'first_name': 'Jim', 'last_name': 'Thome', 'rank': 135, 'team': 'Min', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Kurt', 'last_name': 'Suzuki', 'rank': 136, 'team': 'Oak', 'active': 1, 'position': ['C']},
	{'first_name': 'Hideki', 'last_name': 'Matsui', 'rank': 137, 'team': 'Oak', 'active': 1, 'position': ['LF', 'OF', 'DH']},
	{'first_name': 'Chris', 'last_name': 'Coghlan', 'rank': 138, 'team': 'Fla', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Freddie', 'last_name': 'Freeman', 'rank': 139, 'team': 'Atl', 'active': 1, 'position': ['1B']},
	{'first_name': 'Ryan', 'last_name': 'Raburn', 'rank': 140, 'team': 'Det', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Raul', 'last_name': 'Ibanez', 'rank': 141, 'team': 'Phi', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Franklin', 'last_name': 'Gutierrez', 'rank': 142, 'team': 'Sea', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Austin', 'last_name': 'Jackson', 'rank': 143, 'team': 'Det', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Johnny', 'last_name': 'Damon', 'rank': 144, 'team': 'TB', 'active': 1, 'position': ['LF', 'OF', 'DH']},
	{'first_name': 'Dexter', 'last_name': 'Fowler', 'rank': 145, 'team': 'Col', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Coco', 'last_name': 'Crisp', 'rank': 146, 'team': 'Oak', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Scott', 'last_name': 'Rolen', 'rank': 147, 'team': 'Cin', 'active': 1, 'position': ['3B']},
	{'first_name': 'Scott', 'last_name': 'Podsednik', 'rank': 148, 'team': 'Tor', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Matt', 'last_name': 'Joyce', 'rank': 149, 'team': 'TB', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Garrett', 'last_name': 'Jones', 'rank': 150, 'team': 'Pit', 'active': 1, 'position': ['1B', 'RF', 'OF']},
	{'first_name': 'Seth', 'last_name': 'Smith', 'rank': 151, 'team': 'Col', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Nate', 'last_name': 'McLouth', 'rank': 152, 'team': 'Atl', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Jason', 'last_name': 'Kubel', 'rank': 153, 'team': 'Min', 'active': 1, 'position': ['RF', 'OF', 'DH']},
	{'first_name': 'Mike', 'last_name': 'Aviles', 'rank': 154, 'team': 'KC', 'active': 1, 'position': ['2B']},
	{'first_name': 'Cameron', 'last_name': 'Maybin', 'rank': 155, 'team': 'SD', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Jose', 'last_name': 'Tabata', 'rank': 156, 'team': 'Pit', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Dan', 'last_name': 'Johnson', 'rank': 157, 'team': 'TB', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Julio', 'last_name': 'Borbon', 'rank': 158, 'team': 'Tex', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Justin', 'last_name': 'Smoak', 'rank': 159, 'team': 'Sea', 'active': 1, 'position': ['1B']},
	{'first_name': 'Marlon', 'last_name': 'Byrd', 'rank': 160, 'team': 'ChC', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Logan', 'last_name': 'Morrison', 'rank': 161, 'team': 'Fla', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Jonny', 'last_name': 'Gomes', 'rank': 162, 'team': 'Cin', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Alex', 'last_name': 'Gordon', 'rank': 163, 'team': 'KC', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Cody', 'last_name': 'Ross', 'rank': 164, 'team': 'SF', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'Ty', 'last_name': 'Wigginton', 'rank': 165, 'team': 'Col', 'active': 1, 'position': ['3B', '1B', '2B']},
	{'first_name': 'Ryan', 'last_name': 'Theriot', 'rank': 166, 'team': 'StL', 'active': 1, 'position': ['SS', '2B']},
	{'first_name': 'Tyler', 'last_name': 'Colvin', 'rank': 167, 'team': 'ChC', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'J.D.', 'last_name': 'Drew', 'rank': 168, 'team': 'Bos', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Alfonso', 'last_name': 'Soriano', 'rank': 169, 'team': 'ChC', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Nyjer', 'last_name': 'Morgan', 'rank': 170, 'team': 'Was', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Jhonny', 'last_name': 'Peralta', 'rank': 171, 'team': 'Det', 'active': 1, 'position': ['SS', '3B']},
	{'first_name': 'Magglio', 'last_name': 'Ordonez', 'rank': 172, 'team': 'Det', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Juan', 'last_name': 'Uribe', 'rank': 173, 'team': 'LAD', 'active': 1, 'position': ['2B', '3B', 'SS']},
	{'first_name': 'Peter', 'last_name': 'Bourjos', 'rank': 174, 'team': 'LAA', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Carlos', 'last_name': 'Gomez', 'rank': 175, 'team': 'Mil', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Danny', 'last_name': 'Espinosa', 'rank': 176, 'team': 'Was', 'active': 1, 'position': ['2B']},
	{'first_name': 'Domonic', 'last_name': 'Brown', 'rank': 177, 'team': 'Phi', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Josh', 'last_name': 'Willingham', 'rank': 178, 'team': 'Oak', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Michael', 'last_name': 'Brantley', 'rank': 179, 'team': 'Cle', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'David', 'last_name': 'DeJesus', 'rank': 180, 'team': 'Oak', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Chris', 'last_name': 'Johnson', 'rank': 181, 'team': 'Hou', 'active': 1, 'position': ['3B']},
	{'first_name': 'J.J.', 'last_name': 'Hardy', 'rank': 182, 'team': 'Bal', 'active': 1, 'position': ['SS']},
	{'first_name': 'Pat', 'last_name': 'Burrell', 'rank': 183, 'team': 'SF', 'active': 1, 'position': ['DH', 'LF', 'OF']},
	{'first_name': 'David', 'last_name': 'Murphy', 'rank': 184, 'team': 'Tex', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Daric', 'last_name': 'Barton', 'rank': 185, 'team': 'Oak', 'active': 1, 'position': ['1B']},
	{'first_name': 'Kila', 'last_name': "Ka'aihue", 'rank': 186, 'team': 'KC', 'active': 1, 'position': ['1B']},
	{'first_name': 'Omar', 'last_name': 'Infante', 'rank': 187, 'team': 'Fla', 'active': 1, 'position': ['2B', '3B', 'LF', 'OF']},
	{'first_name': 'Marco', 'last_name': 'Scutaro', 'rank': 188, 'team': 'Bos', 'active': 1, 'position': ['SS']},
	{'first_name': 'Roger', 'last_name': 'Bernadina', 'rank': 189, 'team': 'Was', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'Reid', 'last_name': 'Brignac', 'rank': 190, 'team': 'TB', 'active': 1, 'position': ['SS', '2B']},
	{'first_name': 'Kevin', 'last_name': 'Kouzmanoff', 'rank': 191, 'team': 'Oak', 'active': 1, 'position': ['3B']},
	{'first_name': 'Jorge', 'last_name': 'Posada', 'rank': 192, 'team': 'NYY', 'active': 1, 'position': ['C', 'DH']},
	{'first_name': 'Danny', 'last_name': 'Valencia', 'rank': 193, 'team': 'Min', 'active': 1, 'position': ['3B']},
	{'first_name': 'Miguel', 'last_name': 'Tejada', 'rank': 194, 'team': 'SF', 'active': 1, 'position': ['SS', '3B']},
	{'first_name': 'Alexi', 'last_name': 'Casilla', 'rank': 195, 'team': 'Min', 'active': 1, 'position': ['2B', 'SS']},
	{'first_name': 'Jason', 'last_name': 'Bartlett', 'rank': 196, 'team': 'SD', 'active': 1, 'position': ['SS']},
	{'first_name': 'Will', 'last_name': 'Venable', 'rank': 197, 'team': 'SD', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'Brett', 'last_name': 'Wallace', 'rank': 198, 'team': 'Hou', 'active': 1, 'position': ['1B']},
	{'first_name': 'Chipper', 'last_name': 'Jones', 'rank': 199, 'team': 'Atl', 'active': 1, 'position': ['3B']},
	{'first_name': 'Desmond', 'last_name': 'Jennings', 'rank': 200, 'team': 'TB', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Jack', 'last_name': 'Cust', 'rank': 201, 'team': 'Sea', 'active': 1, 'position': ['LF','OF','DH']},
	{'first_name': 'Brad', 'last_name': 'Hawpe', 'rank': 202, 'team': 'SD', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Bill', 'last_name': 'Hall', 'rank': 203, 'team': 'Hou', 'active': 1, 'position': ['2B', 'LF', 'OF']},
	{'first_name': 'Felix', 'last_name': 'Pie', 'rank': 204, 'team': 'Bal', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Casey', 'last_name': 'Blake', 'rank': 205, 'team': 'LAD', 'active': 1, 'position': ['3B']},
	{'first_name': 'Ryan', 'last_name': 'Ludwick', 'rank': 206, 'team': 'SD', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'J.P.', 'last_name': 'Arencibia', 'rank': 207, 'team': 'Tor', 'active': 1, 'position': ['C']},
	{'first_name': 'Chris', 'last_name': 'Iannetta', 'rank': 208, 'team': 'Col', 'active': 1, 'position': ['C']},
	{'first_name': 'Freddy', 'last_name': 'Sanchez', 'rank': 209, 'team': 'SF', 'active': 1, 'position': ['2B']},
	{'first_name': 'Lyle', 'last_name': 'Overbay', 'rank': 210, 'team': 'Pit', 'active': 1, 'position': ['1B']},
	{'first_name': 'Wilson', 'last_name': 'Betemit', 'rank': 211, 'team': 'KC', 'active': 1, 'position': ['3B']},
	{'first_name': 'Matt', 'last_name': 'Diaz', 'rank': 212, 'team': 'Pit', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Jeff', 'last_name': 'Francoeur', 'rank': 213, 'team': 'KC', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Ben', 'last_name': 'Francisco', 'rank': 214, 'team': 'Phi', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Matt', 'last_name': 'LaPorta', 'rank': 215, 'team': 'Cle', 'active': 1, 'position': ['1B']},
	{'first_name': 'Jay', 'last_name': 'Gibbons', 'rank': 216, 'team': 'LAD', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Orlando', 'last_name': 'Cabrera', 'rank': 217, 'team': 'Cle', 'active': 1, 'position': ['2B', 'SS']},
	{'first_name': 'Kosuke', 'last_name': 'Fukudome', 'rank': 218, 'team': 'ChC', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Yuniesky', 'last_name': 'Betancourt', 'rank': 219, 'team': 'Mil', 'active': 1, 'position': ['SS']},
	{'first_name': 'Chris', 'last_name': 'Heisey', 'rank': 220, 'team': 'Cin', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'Michael', 'last_name': 'Morse', 'rank': 221, 'team': 'Was', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Xavier', 'last_name': 'Nady', 'rank': 222, 'team': 'Ari', 'active': 1, 'position': ['RF', 'OF', '1B']},
	{'first_name': 'Michael', 'last_name': 'Saunders', 'rank': 223, 'team': 'Sea', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Ryan', 'last_name': 'Spilborghs', 'rank': 224, 'team': 'Col', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Carlos', 'last_name': 'Ruiz', 'rank': 225, 'team': 'Phi', 'active': 1, 'position': ['C']},
	{'first_name': 'Yadier', 'last_name': 'Molina', 'rank': 226, 'team': 'StL', 'active': 1, 'position': ['C']},
	{'first_name': 'Travis', 'last_name': 'Hafner', 'rank': 227, 'team': 'Cle', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Skip', 'last_name': 'Schumaker', 'rank': 228, 'team': 'StL', 'active': 1, 'position': ['2B']},
	{'first_name': 'John', 'last_name': 'Buck', 'rank': 229, 'team': 'Fla', 'active': 1, 'position': ['C']},
	{'first_name': 'Brandon', 'last_name': 'Allen', 'rank': 230, 'team': 'Ari', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Juan', 'last_name': 'Miranda', 'rank': 231, 'team': 'Ari', 'active': 1, 'position': ['1B','DH']},
	{'first_name': 'Maicer', 'last_name': 'Izturis', 'rank': 232, 'team': 'LAA', 'active': 1, 'position': ['2B', '3B']},
	{'first_name': 'Jayson', 'last_name': 'Nix', 'rank': 233, 'team': 'Cle', 'active': 1, 'position': ['2B', '3B']},
	{'first_name': 'Cliff', 'last_name': 'Pennington', 'rank': 234, 'team': 'Oak', 'active': 1, 'position': ['SS']},
	{'first_name': 'Nick', 'last_name': 'Hundley', 'rank': 235, 'team': 'SD', 'active': 1, 'position': ['C']},
	{'first_name': 'Alberto', 'last_name': 'Callaspo', 'rank': 236, 'team': 'LAA', 'active': 1, 'position': ['3B']},
	{'first_name': 'Alex', 'last_name': 'Gonzalez', 'rank': 237, 'team': 'Atl', 'active': 1, 'position': ['SS']},
	{'first_name': 'Russell', 'last_name': 'Branyan', 'rank': 238, 'team': 'Ari', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Dustin', 'last_name': 'Ackley', 'rank': 239, 'team': 'Sea', 'active': 1, 'position': ['2B']},
	{'first_name': 'Melvin', 'last_name': 'Mora', 'rank': 240, 'team': 'Ari', 'active': 1, 'position': ['3B', '1B']},
	{'first_name': 'Jon', 'last_name': 'Jay', 'rank': 241, 'team': 'StL', 'active': 1, 'position': ['CF', 'RF', 'OF']},
	{'first_name': 'Eric', 'last_name': 'Young', 'rank': 242, 'team': 'Col', 'active': 1, 'position': ['2B']},
	{'first_name': 'Clint', 'last_name': 'Barmes', 'rank': 243, 'team': 'Hou', 'active': 1, 'position': ['2B', 'SS']},
	{'first_name': 'Miguel', 'last_name': 'Olivo', 'rank': 244, 'team': 'Sea', 'active': 1, 'position': ['C']},
	{'first_name': 'Russell', 'last_name': 'Martin', 'rank': 245, 'team': 'NYY', 'active': 1, 'position': ['C']},
	{'first_name': 'John', 'last_name': 'Jaso', 'rank': 246, 'team': 'TB', 'active': 1, 'position': ['C']},
	{'first_name': 'Milton', 'last_name': 'Bradley', 'rank': 247, 'team': 'Sea', 'active': 1, 'position': ['LF', 'OF', 'DH']},
	{'first_name': 'Mark', 'last_name': 'Ellis', 'rank': 248, 'team': 'Oak', 'active': 1, 'position': ['2B']},
	{'first_name': 'Melky', 'last_name': 'Cabrera', 'rank': 249, 'team': 'KC', 'active': 1, 'position': ['LF', 'CF', 'RF', 'OF']},
	{'first_name': 'Rod', 'last_name': 'Barajas', 'rank': 250, 'team': 'LAD', 'active': 1, 'position': ['C']},
	{'first_name': 'Todd', 'last_name': 'Helton', 'rank': 251, 'team': 'Col', 'active': 1, 'position': ['1B']},
	{'first_name': 'Kyle', 'last_name': 'Blanks', 'rank': 252, 'team': 'SD', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Orlando', 'last_name': 'Hudson', 'rank': 253, 'team': 'SD', 'active': 1, 'position': ['2B']},
	{'first_name': 'Juan', 'last_name': 'Rivera', 'rank': 254, 'team': 'Tor', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Brandon', 'last_name': 'Inge', 'rank': 255, 'team': 'Det', 'active': 1, 'position': ['3B']},
	{'first_name': 'Jose', 'last_name': 'Guillen', 'rank': 256, 'team': 'SF', 'active': 1, 'position': ['RF', 'OF', 'DH']},
	{'first_name': 'Alex', 'last_name': 'Avila', 'rank': 257, 'team': 'Det', 'active': 1, 'position': ['C']},
	{'first_name': 'A.J.', 'last_name': 'Pierzynski', 'rank': 258, 'team': 'CWS', 'active': 1, 'position': ['C']},
	{'first_name': 'Ryan', 'last_name': 'Doumit', 'rank': 259, 'team': 'Pit', 'active': 1, 'position': ['C']},
	{'first_name': 'Conor', 'last_name': 'Jackson', 'rank': 260, 'team': 'Oak', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Chris', 'last_name': 'Dickerson', 'rank': 261, 'team': 'Mil', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Blake', 'last_name': 'DeWitt', 'rank': 262, 'team': 'ChC', 'active': 1, 'position': ['2B']},
	{'first_name': 'Andruw', 'last_name': 'Jones', 'rank': 263, 'team': 'NYY', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Yorvit', 'last_name': 'Torrealba', 'rank': 264, 'team': 'Tex', 'active': 1, 'position': ['C']},
	{'first_name': 'Ramon', 'last_name': 'Hernandez', 'rank': 265, 'team': 'Cin', 'active': 1, 'position': ['C']},
	{'first_name': 'Edgar', 'last_name': 'Renteria', 'rank': 266, 'team': 'Cin', 'active': 1, 'position': ['SS']},
	{'first_name': 'Ronny', 'last_name': 'Cedeno', 'rank': 267, 'team': 'Pit', 'active': 1, 'position': ['SS']},
	{'first_name': 'Eric', 'last_name': 'Hinske', 'rank': 268, 'team': 'Atl', 'active': 1, 'position': ['LF', 'OF', '1B']},
	{'first_name': 'Matt', 'last_name': 'Dominguez', 'rank': 269, 'team': 'Fla', 'active': 1, 'position': ['3B']},
	{'first_name': 'Daniel', 'last_name': 'Murphy', 'rank': 270, 'team': 'NYM', 'active': 1, 'position': ['1B']},
	{'first_name': 'Marcus', 'last_name': 'Thames', 'rank': 271, 'team': 'LAD', 'active': 1, 'position': ['LF', 'OF', 'DH']},
	{'first_name': 'Jesus', 'last_name': 'Montero', 'rank': 272, 'team': 'NYY', 'active': 1, 'position': ['C']},
	{'first_name': 'Mark', 'last_name': 'DeRosa', 'rank': 273, 'team': 'SF', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Aaron', 'last_name': 'Rowand', 'rank': 274, 'team': 'SF', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Jeff', 'last_name': 'Keppinger', 'rank': 275, 'team': 'Hou', 'active': 1, 'position': ['2B']},
	{'first_name': 'Jeff', 'last_name': 'Baker', 'rank': 276, 'team': 'ChC', 'active': 1, 'position': ['2B', '3B']},
	{'first_name': 'Carlos', 'last_name': 'Guillen', 'rank': 277, 'team': 'Det', 'active': 1, 'position': ['2B']},
	{'first_name': 'Nolan', 'last_name': 'Reimold', 'rank': 278, 'team': 'Bal', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Brayan', 'last_name': 'Pena', 'rank': 279, 'team': 'KC', 'active': 1, 'position': ['C']},
	{'first_name': 'Brent', 'last_name': 'Morel', 'rank': 280, 'team': 'CWS', 'active': 1, 'position': ['3B']},
	{'first_name': 'Chris', 'last_name': 'Snyder', 'rank': 281, 'team': 'Pit', 'active': 1, 'position': ['C']},
	{'first_name': 'Rick', 'last_name': 'Ankiel', 'rank': 282, 'team': 'Was', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Jake', 'last_name': 'Fox', 'rank': 283, 'team': 'Bal', 'active': 1, 'position': ['1B', 'DH']},
	{'first_name': 'Adam', 'last_name': 'Kennedy', 'rank': 284, 'team': 'Sea', 'active': 1, 'position': ['2B', '1B']},
	{'first_name': 'Jonathan', 'last_name': 'Lucroy', 'rank': 285, 'team': 'Mil', 'active': 1, 'position': ['C']},
	{'first_name': 'Brendan', 'last_name': 'Ryan', 'rank': 286, 'team': 'Sea', 'active': 1, 'position': ['SS']},
	{'first_name': 'Scott', 'last_name': 'Sizemore', 'rank': 287, 'team': 'Det', 'active': 1, 'position': ['2B']},
	{'first_name': 'Adam', 'last_name': 'Rosales', 'rank': 288, 'team': 'Oak', 'active': 1, 'position': ['2B']},
	{'first_name': 'Jed', 'last_name': 'Lowrie', 'rank': 289, 'team': 'Bos', 'active': 1, 'position': ['SS', '2B']},
	{'first_name': 'Lastings', 'last_name': 'Milledge', 'rank': 290, 'team': 'CWS', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Jarrod', 'last_name': 'Saltalamacchia', 'rank': 291, 'team': 'Bos', 'active': 1, 'position': ['C']},
	{'first_name': 'Corey', 'last_name': 'Patterson', 'rank': 292, 'team': 'Tor', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Eduardo', 'last_name': 'Nunez', 'rank': 293, 'team': 'NYY', 'active': 1, 'position': ['3B']},
	{'first_name': 'Jamey', 'last_name': 'Carroll', 'rank': 294, 'team': 'LAD', 'active': 1, 'position': ['2B', 'SS']},
	{'first_name': 'Mat', 'last_name': 'Gamel', 'rank': 295, 'team': 'Mil', 'active': 1, 'position': ['3B']},
	{'first_name': 'Jorge', 'last_name': 'Cantu', 'rank': 296, 'team': 'SD', 'active': 1, 'position': ['3B', '1B']},
	{'first_name': 'Brooks', 'last_name': 'Conrad', 'rank': 297, 'team': 'Atl', 'active': 1, 'position': ['3B']},
	{'first_name': 'Troy', 'last_name': 'Glaus', 'rank': 298, 'team': 'Atl', 'active': 1, 'position': ['1B']},
	{'first_name': 'Willie', 'last_name': 'Bloomquist', 'rank': 299, 'team': 'Ari', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Willie', 'last_name': 'Harris', 'rank': 300, 'team': 'NYM', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Emilio', 'last_name': 'Bonifacio', 'rank': 301, 'team': 'Fla', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Ryan', 'last_name': 'Hanigan', 'rank': 302, 'team': 'Cin', 'active': 1, 'position': ['C']},
	{'first_name': 'Juan', 'last_name': 'Francisco', 'rank': 303, 'team': 'Cin', 'active': 1, 'position': ['3B']},
	{'first_name': 'Mike', 'last_name': 'Cameron', 'rank': 304, 'team': 'Bos', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Josh', 'last_name': 'Thole', 'rank': 305, 'team': 'NYM', 'active': 1, 'position': ['C']},
	{'first_name': 'Scott', 'last_name': 'Hairston', 'rank': 306, 'team': 'NYM', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Felipe', 'last_name': 'Lopez', 'rank': 307, 'team': 'TB', 'active': 1, 'position': ['2B', '3B', 'SS']},
	{'first_name': 'Geoff', 'last_name': 'Blum', 'rank': 308, 'team': 'Ari', 'active': 1, 'position': ['SS']},
	{'first_name': 'Mike', 'last_name': 'Moustakas', 'rank': 309, 'team': 'KC', 'active': 1, 'position': ['3B']},
	{'first_name': 'Lorenzo', 'last_name': 'Cain', 'rank': 310, 'team': 'KC', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Brennan', 'last_name': 'Boesch', 'rank': 311, 'team': 'Det', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Chris', 'last_name': 'Denorfia', 'rank': 312, 'team': 'SD', 'active': 1, 'position': ['LF', 'CF', 'OF']},
	{'first_name': 'Ross', 'last_name': 'Gload', 'rank': 313, 'team': 'Phi', 'active': 1, 'position': ['1B']},
	{'first_name': 'Chris', 'last_name': 'Getz', 'rank': 314, 'team': 'KC', 'active': 1, 'position': ['2B']},
	{'first_name': 'Allen', 'last_name': 'Craig', 'rank': 315, 'team': 'StL', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Jerry', 'last_name': 'Hairston', 'rank': 316, 'team': 'Was', 'active': 1, 'position': ['SS', '2B']},
	{'first_name': 'Luis', 'last_name': 'Castillo', 'rank': 317, 'team': 'NYM', 'active': 1, 'position': ['2B']},
	{'first_name': 'Ryan', 'last_name': 'Sweeney', 'rank': 318, 'team': 'Oak', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Ronny', 'last_name': 'Paulino', 'rank': 319, 'team': 'NYM', 'active': 1, 'position': ['C']},
	{'first_name': 'Tyler', 'last_name': 'Greene', 'rank': 320, 'team': 'StL', 'active': 1, 'position': ['SS']},
	{'first_name': 'Jesus', 'last_name': 'Flores', 'rank': 321, 'team': 'Was', 'active': 1, 'position': ['C']},
	{'first_name': 'Randy', 'last_name': 'Winn', 'rank': 322, 'team': 'Bal', 'active': 1, 'position': ['OF']},
	{'first_name': 'Willy', 'last_name': 'Aybar', 'rank': 323, 'team': 'FA', 'active': 1, 'position': ['DH']},
	{'first_name': 'Ramon', 'last_name': 'Castro', 'rank': 324, 'team': 'CWS', 'active': 1, 'position': ['C']},
	{'first_name': 'Nate', 'last_name': 'Schierholtz', 'rank': 325, 'team': 'SF', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Nick', 'last_name': 'Johnson', 'rank': 326, 'team': 'FA', 'active': 1, 'position': ['DH']},
	{'first_name': 'Ivan', 'last_name': 'Rodriguez', 'rank': 327, 'team': 'Was', 'active': 1, 'position': ['C']},
	{'first_name': 'John', 'last_name': 'Bowker', 'rank': 328, 'team': 'Pit', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Brandon', 'last_name': 'Belt', 'rank': 329, 'team': 'SF', 'active': 1, 'position': ['1B']},
	{'first_name': 'Xavier', 'last_name': 'Paul', 'rank': 330, 'team': 'LAD', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Jason', 'last_name': 'Donald', 'rank': 331, 'team': 'Cle', 'active': 1, 'position': ['SS', '2B']},
	{'first_name': 'Reed', 'last_name': 'Johnson', 'rank': 332, 'team': 'ChC', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Austin', 'last_name': 'Kearns', 'rank': 333, 'team': 'Cle', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Jason', 'last_name': 'Michaels', 'rank': 334, 'team': 'Hou', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Miguel', 'last_name': 'Cairo', 'rank': 335, 'team': 'Cin', 'active': 1, 'position': ['3B']},
	{'first_name': 'Kelly', 'last_name': 'Shoppach', 'rank': 336, 'team': 'TB', 'active': 1, 'position': ['C']},
	{'first_name': 'Nick', 'last_name': 'Evans', 'rank': 337, 'team': 'NYM', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Travis', 'last_name': 'Ishikawa', 'rank': 338, 'team': 'SF', 'active': 1, 'position': ['1B']},
	{'first_name': 'Tony', 'last_name': 'Gwynn', 'rank': 339, 'team': 'LAD', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Laynce', 'last_name': 'Nix', 'rank': 340, 'team': 'Was', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Jason', 'last_name': 'Giambi', 'rank': 341, 'team': 'Col', 'active': 1, 'position': ['1B']},
	{'first_name': 'John', 'last_name': 'Mayberry', 'rank': 342, 'team': 'Phi', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Justin', 'last_name': 'Ruggiano', 'rank': 343, 'team': 'FA', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Jason', 'last_name': 'Varitek', 'rank': 344, 'team': 'Bos', 'active': 1, 'position': ['C']},
	{'first_name': 'Fernando', 'last_name': 'Martinez', 'rank': 345, 'team': 'NYM', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Yonder', 'last_name': 'Alonso', 'rank': 346, 'team': 'Cin', 'active': 1, 'position': ['1B']},
	{'first_name': 'Mike', 'last_name': 'Fontenot', 'rank': 347, 'team': 'SF', 'active': 1, 'position': ['2B', '3B']},
	{'first_name': 'Shelley', 'last_name': 'Duncan', 'rank': 348, 'team': 'Cle', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'George', 'last_name': 'Kottaras', 'rank': 349, 'team': 'Mil', 'active': 1, 'position': ['C']},
	{'first_name': 'Everth', 'last_name': 'Cabrera', 'rank': 350, 'team': 'SD', 'active': 1, 'position': ['SS']},
	{'first_name': 'Mike', 'last_name': 'Sweeney', 'rank': 351, 'team': 'FA', 'active': 1, 'position': ['DH']},
	{'first_name': 'Bengie', 'last_name': 'Molina', 'rank': 352, 'team': 'FA', 'active': 1, 'position': ['C']},
	{'first_name': 'Scott', 'last_name': 'Cousins', 'rank': 353, 'team': 'Fla', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Gerardo', 'last_name': 'Parra', 'rank': 354, 'team': 'Ari', 'active': 1, 'position': ['LF', 'RF', 'OF']},
	{'first_name': 'Jason', 'last_name': 'Kipnis', 'rank': 355, 'team': 'Cle', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Mark', 'last_name': 'Teahen', 'rank': 356, 'team': 'CWS', 'active': 1, 'position': ['3B']},
	{'first_name': 'Jason', 'last_name': 'Castro', 'rank': 357, 'team': 'Hou', 'active': 1, 'position': ['C']},
	{'first_name': 'Ryan', 'last_name': 'Roberts', 'rank': 358, 'team': 'Ari', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Chris', 'last_name': 'Davis', 'rank': 359, 'team': 'Tex', 'active': 1, 'position': ['1B']},
	{'first_name': 'Lou', 'last_name': 'Marson', 'rank': 360, 'team': 'Cle', 'active': 1, 'position': ['C']},
	{'first_name': 'Don', 'last_name': 'Kelly', 'rank': 361, 'team': 'Det', 'active': 1, 'position': ['LF', 'OF', '1B']},
	{'first_name': 'John', 'last_name': 'Baker', 'rank': 362, 'team': 'Fla', 'active': 1, 'position': ['C']},
	{'first_name': 'Paul', 'last_name': 'Janish', 'rank': 363, 'team': 'Cin', 'active': 1, 'position': ['SS']},
	{'first_name': 'Will', 'last_name': 'Rhymes', 'rank': 364, 'team': 'Det', 'active': 1, 'position': ['2B']},
	{'first_name': 'Wilson', 'last_name': 'Ramos', 'rank': 365, 'team': 'Was', 'active': 1, 'position': ['C']},
	{'first_name': 'Brad', 'last_name': 'Emaus', 'rank': 366, 'team': 'NYM', 'active': 1, 'position': ['2B']},
	{'first_name': 'Joe', 'last_name': 'Inglett', 'rank': 367, 'team': 'FA', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Joe', 'last_name': 'Mather', 'rank': 368, 'team': 'Atl', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Ramon', 'last_name': 'Santiago', 'rank': 369, 'team': 'Det', 'active': 1, 'position': ['2B', 'SS']},
	{'first_name': 'Wes', 'last_name': 'Helms', 'rank': 370, 'team': 'Fla', 'active': 1, 'position': ['3B']},
	{'first_name': 'Chris', 'last_name': 'Carter', 'rank': 371, 'team': 'Oak', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Sam', 'last_name': 'Fuld', 'rank': 372, 'team': 'TB', 'active': 1, 'position': ['LF', 'OF']},
	{'first_name': 'Chris', 'last_name': 'Valaika', 'rank': 373, 'team': 'Cin', 'active': 1, 'position': ['2B']},
	{'first_name': 'Wilson', 'last_name': 'Valdez', 'rank': 374, 'team': 'Phi', 'active': 1, 'position': ['SS', '2B']},
	{'first_name': 'Colin', 'last_name': 'Curtis', 'rank': 375, 'team': 'NYY', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Ryan', 'last_name': 'Kalish', 'rank': 376, 'team': 'Bos', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Nick', 'last_name': 'Stavinoha', 'rank': 377, 'team': 'StL', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Trevor', 'last_name': 'Crowe', 'rank': 378, 'team': 'Cle', 'active': 1, 'position': ['LF', 'CF', 'OF']},
	{'first_name': 'Robinson', 'last_name': 'Chirinos', 'rank': 379, 'team': 'TB', 'active': 1, 'position': ['C']},
	{'first_name': 'Luis', 'last_name': 'Valbuena', 'rank': 380, 'team': 'Cle', 'active': 1, 'position': ['2B']},
	{'first_name': 'Andy', 'last_name': 'Marte', 'rank': 381, 'team': 'Pit', 'active': 1, 'position': ['1B', '3B']},
	{'first_name': 'Mike', 'last_name': 'McCoy', 'rank': 382, 'team': 'Tor', 'active': 1, 'position': ['2B']},
	{'first_name': 'Leslie', 'last_name': 'Anderson', 'rank': 383, 'team': 'FA', 'active': 1, 'position': ['1B']},
	{'first_name': 'Steve', 'last_name': 'Pearce', 'rank': 384, 'team': 'Pit', 'active': 1, 'position': ['1B']},
	{'first_name': 'Craig', 'last_name': 'Counsell', 'rank': 385, 'team': 'Mil', 'active': 1, 'position': ['SS', '3B']},
	{'first_name': 'Casper', 'last_name': 'Wells', 'rank': 386, 'team': 'Det', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Adam', 'last_name': 'Moore', 'rank': 387, 'team': 'Sea', 'active': 1, 'position': ['C']},
	{'first_name': 'Eric', 'last_name': 'Patterson', 'rank': 388, 'team': 'SD', 'active': 1, 'position': ['LF', 'CF', 'OF']},
	{'first_name': 'Chad', 'last_name': 'Tracy', 'rank': 389, 'team': 'FA', 'active': 1, 'position': ['3B']},
	{'first_name': 'Jason', 'last_name': 'Repko', 'rank': 390, 'team': 'Min', 'active': 1, 'position': ['RF', 'OF']},
	{'first_name': 'Gregor', 'last_name': 'Blanco', 'rank': 391, 'team': 'KC', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Diory', 'last_name': 'Hernandez', 'rank': 392, 'team': 'Atl', 'active': 1, 'position': ['SS']},
	{'first_name': 'David', 'last_name': 'Ross', 'rank': 393, 'team': 'Atl', 'active': 1, 'position': ['C']},
	{'first_name': 'David', 'last_name': 'Eckstein', 'rank': 394, 'team': 'FA', 'active': 1, 'position': ['2B']},
	{'first_name': 'Francisco', 'last_name': 'Cervelli', 'rank': 395, 'team': 'NYY', 'active': 1, 'position': ['C']},
	{'first_name': 'Casey', 'last_name': 'Kotchman', 'rank': 396, 'team': 'TB', 'active': 1, 'position': ['1B']},
	{'first_name': 'Ben', 'last_name': 'Revere', 'rank': 397, 'team': 'Min', 'active': 1, 'position': ['CF', 'OF']},
	{'first_name': 'Gregg', 'last_name': 'Zaun', 'rank': 398, 'team': 'SD', 'active': 1, 'position': ['C']},
	{'first_name': 'Josh', 'last_name': 'Rodriguez', 'rank': 399, 'team': 'Pit', 'active': 1, 'position': ['SS']},
	{'first_name': 'Angel', 'last_name': 'Sanchez', 'rank': 400, 'team': 'Hou', 'active': 1, 'position': ['SS']},
	{'first_name': 'Roy', 'last_name': 'Halladay', 'rank': 1, 'team': 'Phi', 'active': 1, 'position': ['SP']},
	{'first_name': 'Felix', 'last_name': 'Hernandez', 'rank': 2, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tim', 'last_name': 'Lincecum', 'rank': 3, 'team': 'SF', 'active': 1, 'position': ['SP']},
	{'first_name': 'Cliff', 'last_name': 'Lee', 'rank': 4, 'team': 'Phi', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jon', 'last_name': 'Lester', 'rank': 5, 'team': 'Bos', 'active': 1, 'position': ['SP']},
	{'first_name': 'Adam', 'last_name': 'Wainwright', 'rank': 6, 'team': 'StL', 'active': 1, 'position': ['SP']},
	{'first_name': 'CC', 'last_name': 'Sabathia', 'rank': 7, 'team': 'NYY', 'active': 1, 'position': ['SP']},
	{'first_name': 'Clayton', 'last_name': 'Kershaw', 'rank': 8, 'team': 'LAD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Zack', 'last_name': 'Greinke', 'rank': 9, 'team': 'Mil', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tommy', 'last_name': 'Hanson', 'rank': 10, 'team': 'Atl', 'active': 1, 'position': ['SP']},
	{'first_name': 'Justin', 'last_name': 'Verlander', 'rank': 11, 'team': 'Det', 'active': 1, 'position': ['SP']},
	{'first_name': 'Chris', 'last_name': 'Carpenter', 'rank': 12, 'team': 'StL', 'active': 1, 'position': ['SP']},
	{'first_name': 'Ubaldo', 'last_name': 'Jimenez', 'rank': 13, 'team': 'Col', 'active': 1, 'position': ['SP']},
	{'first_name': 'Dan', 'last_name': 'Haren', 'rank': 14, 'team': 'LAA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Mat', 'last_name': 'Latos', 'rank': 15, 'team': 'SD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jered', 'last_name': 'Weaver', 'rank': 16, 'team': 'LAA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Cole', 'last_name': 'Hamels', 'rank': 17, 'team': 'Phi', 'active': 1, 'position': ['SP']},
	{'first_name': 'Brian', 'last_name': 'Wilson', 'rank': 18, 'team': 'SF', 'active': 1, 'position': ['RP']},
	{'first_name': 'Josh', 'last_name': 'Johnson', 'rank': 19, 'team': 'Fla', 'active': 1, 'position': ['SP']},
	{'first_name': 'Matt', 'last_name': 'Cain', 'rank': 20, 'team': 'SF', 'active': 1, 'position': ['SP']},
	{'first_name': 'Heath', 'last_name': 'Bell', 'rank': 21, 'team': 'SD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Roy', 'last_name': 'Oswalt', 'rank': 22, 'team': 'Phi', 'active': 1, 'position': ['SP']},
	{'first_name': 'Mariano', 'last_name': 'Rivera', 'rank': 23, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'David', 'last_name': 'Price', 'rank': 24, 'team': 'TB', 'active': 1, 'position': ['SP']},
	{'first_name': 'Joakim', 'last_name': 'Soria', 'rank': 25, 'team': 'KC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Yovani', 'last_name': 'Gallardo', 'rank': 26, 'team': 'Mil', 'active': 1, 'position': ['SP']},
	{'first_name': 'Francisco', 'last_name': 'Liriano', 'rank': 27, 'team': 'Min', 'active': 1, 'position': ['SP']},
	{'first_name': 'Neftali', 'last_name': 'Feliz', 'rank': 28, 'team': 'Tex', 'active': 1, 'position': ['RP']},
	{'first_name': 'Max', 'last_name': 'Scherzer', 'rank': 29, 'team': 'Det', 'active': 1, 'position': ['SP']},
	{'first_name': 'Wandy', 'last_name': 'Rodriguez', 'rank': 30, 'team': 'Hou', 'active': 1, 'position': ['SP']},
	{'first_name': 'Carlos', 'last_name': 'Marmol', 'rank': 31, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chad', 'last_name': 'Billingsley', 'rank': 32, 'team': 'LAD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Ted', 'last_name': 'Lilly', 'rank': 33, 'team': 'LAD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Francisco', 'last_name': 'Rodriguez', 'rank': 34, 'team': 'NYM', 'active': 1, 'position': ['RP']},
	{'first_name': 'Shaun', 'last_name': 'Marcum', 'rank': 35, 'team': 'Mil', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jonathan', 'last_name': 'Papelbon', 'rank': 36, 'team': 'Bos', 'active': 1, 'position': ['RP']},
	{'first_name': 'Matt', 'last_name': 'Garza', 'rank': 37, 'team': 'ChC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jonathan', 'last_name': 'Broxton', 'rank': 38, 'team': 'LAD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Tim', 'last_name': 'Hudson', 'rank': 39, 'team': 'Atl', 'active': 1, 'position': ['SP']},
	{'first_name': 'Brett', 'last_name': 'Anderson', 'rank': 40, 'team': 'Oak', 'active': 1, 'position': ['SP']},
	{'first_name': 'Hiroki', 'last_name': 'Kuroda', 'rank': 41, 'team': 'LAD', 'active': 1, 'position': ['SP']},
	{'first_name': 'John', 'last_name': 'Danks', 'rank': 42, 'team': 'CWS', 'active': 1, 'position': ['SP']},
	{'first_name': 'J.J.', 'last_name': 'Putz', 'rank': 43, 'team': 'Ari', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jonathan', 'last_name': 'Sanchez', 'rank': 44, 'team': 'SF', 'active': 1, 'position': ['SP']},
	{'first_name': 'Clay', 'last_name': 'Buchholz', 'rank': 45, 'team': 'Bos', 'active': 1, 'position': ['SP']},
	{'first_name': 'Andrew', 'last_name': 'Bailey', 'rank': 46, 'team': 'Oak', 'active': 1, 'position': ['RP']},
	{'first_name': 'Daniel', 'last_name': 'Hudson', 'rank': 47, 'team': 'Ari', 'active': 1, 'position': ['SP']},
	{'first_name': 'Chris', 'last_name': 'Perez', 'rank': 48, 'team': 'Cle', 'active': 1, 'position': ['RP']},
	{'first_name': 'Colby', 'last_name': 'Lewis', 'rank': 49, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'Brett', 'last_name': 'Myers', 'rank': 50, 'team': 'Hou', 'active': 1, 'position': ['SP']},
	{'first_name': 'John', 'last_name': 'Axford', 'rank': 51, 'team': 'Mil', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jeremy', 'last_name': 'Hellickson', 'rank': 52, 'team': 'TB', 'active': 1, 'position': ['SP']},
	{'first_name': 'Huston', 'last_name': 'Street', 'rank': 53, 'team': 'Col', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brandon', 'last_name': 'Morrow', 'rank': 54, 'team': 'Tor', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jose', 'last_name': 'Valverde', 'rank': 55, 'team': 'Det', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jhoulys', 'last_name': 'Chacin', 'rank': 56, 'team': 'Col', 'active': 1, 'position': ['SP']},
	{'first_name': 'Ricky', 'last_name': 'Nolasco', 'rank': 57, 'team': 'Fla', 'active': 1, 'position': ['SP']},
	{'first_name': 'Drew', 'last_name': 'Storen', 'rank': 58, 'team': 'Was', 'active': 1, 'position': ['RP']},
	{'first_name': 'Francisco', 'last_name': 'Cordero', 'rank': 59, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Johnny', 'last_name': 'Cueto', 'rank': 60, 'team': 'Cin', 'active': 1, 'position': ['SP']},
	{'first_name': 'Phil', 'last_name': 'Hughes', 'rank': 61, 'team': 'NYY', 'active': 1, 'position': ['SP']},
	{'first_name': 'Ryan', 'last_name': 'Franklin', 'rank': 62, 'team': 'StL', 'active': 1, 'position': ['RP']},
	{'first_name': 'Madison', 'last_name': 'Bumgarner', 'rank': 63, 'team': 'SF', 'active': 1, 'position': ['SP']},
	{'first_name': 'Joe', 'last_name': 'Nathan', 'rank': 64, 'team': 'Min', 'active': 1, 'position': ['RP']},
	{'first_name': 'Ryan', 'last_name': 'Dempster', 'rank': 65, 'team': 'ChC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Trevor', 'last_name': 'Cahill', 'rank': 66, 'team': 'Oak', 'active': 1, 'position': ['SP']},
	{'first_name': 'Craig', 'last_name': 'Kimbrel', 'rank': 67, 'team': 'Atl', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jaime', 'last_name': 'Garcia', 'rank': 68, 'team': 'StL', 'active': 1, 'position': ['SP']},
	{'first_name': 'Ricky', 'last_name': 'Romero', 'rank': 69, 'team': 'Tor', 'active': 1, 'position': ['SP']},
	{'first_name': 'Brian', 'last_name': 'Matusz', 'rank': 70, 'team': 'Bal', 'active': 1, 'position': ['SP']},
	{'first_name': 'Matt', 'last_name': 'Thornton', 'rank': 71, 'team': 'CWS', 'active': 1, 'position': ['RP']},
	{'first_name': 'Josh', 'last_name': 'Beckett', 'rank': 72, 'team': 'Bos', 'active': 1, 'position': ['SP']},
	{'first_name': 'C.J.', 'last_name': 'Wilson', 'rank': 73, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'Ian', 'last_name': 'Kennedy', 'rank': 74, 'team': 'Ari', 'active': 1, 'position': ['SP']},
	{'first_name': 'Frank', 'last_name': 'Francisco', 'rank': 75, 'team': 'Tor', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jordan', 'last_name': 'Zimmermann', 'rank': 76, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Brad', 'last_name': 'Lidge', 'rank': 77, 'team': 'Phi', 'active': 1, 'position': ['RP']},
	{'first_name': 'Edinson', 'last_name': 'Volquez', 'rank': 78, 'team': 'Cin', 'active': 1, 'position': ['SP']},
	{'first_name': 'Brandon', 'last_name': 'Lyon', 'rank': 79, 'team': 'Hou', 'active': 1, 'position': ['RP']},
	{'first_name': 'Bronson', 'last_name': 'Arroyo', 'rank': 80, 'team': 'Cin', 'active': 1, 'position': ['SP']},
	{'first_name': 'James', 'last_name': 'Shields', 'rank': 81, 'team': 'TB', 'active': 1, 'position': ['SP']},
	{'first_name': 'Leo', 'last_name': 'Nunez', 'rank': 82, 'team': 'Fla', 'active': 1, 'position': ['RP']},
	{'first_name': 'Travis', 'last_name': 'Wood', 'rank': 83, 'team': 'Cin', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kevin', 'last_name': 'Gregg', 'rank': 84, 'team': 'Bal', 'active': 1, 'position': ['RP']},
	{'first_name': 'Fernando', 'last_name': 'Rodney', 'rank': 85, 'team': 'LAA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jair', 'last_name': 'Jurrjens', 'rank': 86, 'team': 'Atl', 'active': 1, 'position': ['SP']},
	{'first_name': 'Wade', 'last_name': 'Davis', 'rank': 87, 'team': 'TB', 'active': 1, 'position': ['SP']},
	{'first_name': 'Evan', 'last_name': 'Meek', 'rank': 88, 'team': 'Pit', 'active': 1, 'position': ['RP']},
	{'first_name': 'Joel', 'last_name': 'Pineiro', 'rank': 89, 'team': 'LAA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Hong-Chih', 'last_name': 'Kuo', 'rank': 90, 'team': 'LAD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Johan', 'last_name': 'Santana', 'rank': 91, 'team': 'NYM', 'active': 1, 'position': ['SP']},
	{'first_name': 'Gavin', 'last_name': 'Floyd', 'rank': 92, 'team': 'CWS', 'active': 1, 'position': ['SP']},
	{'first_name': 'Anibal', 'last_name': 'Sanchez', 'rank': 93, 'team': 'Fla', 'active': 1, 'position': ['SP']},
	{'first_name': 'Chris', 'last_name': 'Sale', 'rank': 94, 'team': 'CWS', 'active': 1, 'position': ['RP']},
	{'first_name': 'Randy', 'last_name': 'Wolf', 'rank': 95, 'team': 'Mil', 'active': 1, 'position': ['SP']},
	{'first_name': 'James', 'last_name': 'McDonald', 'rank': 96, 'team': 'Pit', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jon', 'last_name': 'Garland', 'rank': 97, 'team': 'LAD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jake', 'last_name': 'McGee', 'rank': 98, 'team': 'TB', 'active': 1, 'position': ['RP']},
	{'first_name': 'Michael', 'last_name': 'Pineda', 'rank': 99, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Ryan', 'last_name': 'Madson', 'rank': 100, 'team': 'Phi', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jake', 'last_name': 'Westbrook', 'rank': 101, 'team': 'StL', 'active': 1, 'position': ['SP']},
	{'first_name': 'Scott', 'last_name': 'Baker', 'rank': 102, 'team': 'Min', 'active': 1, 'position': ['SP']},
	{'first_name': 'John', 'last_name': 'Lackey', 'rank': 103, 'team': 'Bos', 'active': 1, 'position': ['SP']},
	{'first_name': 'Daniel', 'last_name': 'Bard', 'rank': 104, 'team': 'Bos', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jorge', 'last_name': 'De', 'rank': 105, 'team': 'Col', 'active': 1, 'position': ['SP']},
	{'first_name': 'Dallas', 'last_name': 'Braden', 'rank': 106, 'team': 'Oak', 'active': 1, 'position': ['SP']},
	{'first_name': 'Joel', 'last_name': 'Hanrahan', 'rank': 107, 'team': 'Pit', 'active': 1, 'position': ['RP']},
	{'first_name': 'Octavio', 'last_name': 'Dotel', 'rank': 108, 'team': 'Tor', 'active': 1, 'position': ['RP']},
	{'first_name': 'Javier', 'last_name': 'Vazquez', 'rank': 109, 'team': 'Fla', 'active': 1, 'position': ['SP']},
	{'first_name': 'Sergio', 'last_name': 'Romo', 'rank': 110, 'team': 'SF', 'active': 1, 'position': ['RP']},
	{'first_name': 'Rafael', 'last_name': 'Soriano', 'rank': 111, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'Luke', 'last_name': 'Gregerson', 'rank': 112, 'team': 'SD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Ervin', 'last_name': 'Santana', 'rank': 113, 'team': 'LAA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kevin', 'last_name': 'Slowey', 'rank': 114, 'team': 'Min', 'active': 1, 'position': ['SP']},
	{'first_name': 'Rafael', 'last_name': 'Betancourt', 'rank': 115, 'team': 'Col', 'active': 1, 'position': ['RP']},
	{'first_name': 'Edwin', 'last_name': 'Jackson', 'rank': 116, 'team': 'CWS', 'active': 1, 'position': ['SP']},
	{'first_name': 'R.A.', 'last_name': 'Dickey', 'rank': 117, 'team': 'NYM', 'active': 1, 'position': ['SP']},
	{'first_name': 'Alexi', 'last_name': 'Ogando', 'rank': 118, 'team': 'Tex', 'active': 1, 'position': ['RP']},
	{'first_name': 'Gio', 'last_name': 'Gonzalez', 'rank': 119, 'team': 'Oak', 'active': 1, 'position': ['SP']},
	{'first_name': 'Rick', 'last_name': 'Porcello', 'rank': 120, 'team': 'Det', 'active': 1, 'position': ['SP']},
	{'first_name': 'Mike', 'last_name': 'Adams', 'rank': 121, 'team': 'SD', 'active': 1, 'position': ['RP']},
	{'first_name': 'J.A.', 'last_name': 'Happ', 'rank': 122, 'team': 'Hou', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kyle', 'last_name': 'Drabek', 'rank': 123, 'team': 'Tor', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jake', 'last_name': 'Peavy', 'rank': 124, 'team': 'CWS', 'active': 1, 'position': ['SP']},
	{'first_name': 'Carlos', 'last_name': 'Zambrano', 'rank': 125, 'team': 'ChC', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Brian', 'last_name': 'Duensing', 'rank': 126, 'team': 'Min', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Joaquin', 'last_name': 'Benoit', 'rank': 127, 'team': 'Det', 'active': 1, 'position': ['RP']},
	{'first_name': 'Tim', 'last_name': 'Stauffer', 'rank': 128, 'team': 'SD', 'active': 1, 'position': ['RP', 'SP']},
	{'first_name': 'Aroldis', 'last_name': 'Chapman', 'rank': 129, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brett', 'last_name': 'Cecil', 'rank': 130, 'team': 'Tor', 'active': 1, 'position': ['SP']},
	{'first_name': 'David', 'last_name': 'Aardsma', 'rank': 131, 'team': 'Sea', 'active': 1, 'position': ['RP']},
	{'first_name': 'Carl', 'last_name': 'Pavano', 'rank': 132, 'team': 'Min', 'active': 1, 'position': ['SP']},
	{'first_name': 'Joel', 'last_name': 'Peralta', 'rank': 133, 'team': 'TB', 'active': 1, 'position': ['RP']},
	{'first_name': 'Derek', 'last_name': 'Holland', 'rank': 134, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'Scott', 'last_name': 'Downs', 'rank': 135, 'team': 'LAA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kyle', 'last_name': 'McClellan', 'rank': 136, 'team': 'StL', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brandon', 'last_name': 'League', 'rank': 137, 'team': 'Sea', 'active': 1, 'position': ['RP']},
	{'first_name': 'Andy', 'last_name': 'Pettitte', 'rank': 138, 'team': 'FA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeremy', 'last_name': 'Guthrie', 'rank': 139, 'team': 'Bal', 'active': 1, 'position': ['SP']},
	{'first_name': 'Aaron', 'last_name': 'Harang', 'rank': 140, 'team': 'SD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tyler', 'last_name': 'Clippard', 'rank': 141, 'team': 'Was', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chris', 'last_name': 'Narveson', 'rank': 142, 'team': 'Mil', 'active': 1, 'position': ['RP', 'SP']},
	{'first_name': 'Brandon', 'last_name': 'Webb', 'rank': 143, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'Matt', 'last_name': 'Guerrier', 'rank': 144, 'team': 'LAD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Vicente', 'last_name': 'Padilla', 'rank': 145, 'team': 'LAD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Matt', 'last_name': 'Capps', 'rank': 146, 'team': 'Min', 'active': 1, 'position': ['RP']},
	{'first_name': 'Clay', 'last_name': 'Hensley', 'rank': 147, 'team': 'Fla', 'active': 1, 'position': ['RP']},
	{'first_name': 'Takashi', 'last_name': 'Saito', 'rank': 148, 'team': 'Mil', 'active': 1, 'position': ['RP']},
	{'first_name': 'Nick', 'last_name': 'Masset', 'rank': 149, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Logan', 'last_name': 'Ondrusek', 'rank': 150, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Randy', 'last_name': 'Wells', 'rank': 151, 'team': 'ChC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Grant', 'last_name': 'Balfour', 'rank': 152, 'team': 'Oak', 'active': 1, 'position': ['RP']},
	{'first_name': 'Darren', 'last_name': "O'Day", 'rank': 153, 'team': 'Tex', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jonny', 'last_name': 'Venters', 'rank': 154, 'team': 'Atl', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mike', 'last_name': 'Pelfrey', 'rank': 155, 'team': 'NYM', 'active': 1, 'position': ['SP']},
	{'first_name': 'Phil', 'last_name': 'Coke', 'rank': 156, 'team': 'Det', 'active': 1, 'position': ['RP']},
	{'first_name': 'Derek', 'last_name': 'Lowe', 'rank': 157, 'team': 'Atl', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kameron', 'last_name': 'Loe', 'rank': 158, 'team': 'Mil', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kenley', 'last_name': 'Jansen', 'rank': 159, 'team': 'LAD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Craig', 'last_name': 'Breslow', 'rank': 160, 'team': 'Oak', 'active': 1, 'position': ['RP']},
	{'first_name': 'Hisanori', 'last_name': 'Takahashi', 'rank': 161, 'team': 'LAA', 'active': 1, 'position': ['RP', 'SP']},
	{'first_name': 'Jason', 'last_name': 'Frasor', 'rank': 162, 'team': 'Tor', 'active': 1, 'position': ['RP']},
	{'first_name': 'Arthur', 'last_name': 'Rhodes', 'rank': 163, 'team': 'Tex', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mike', 'last_name': 'Gonzalez', 'rank': 164, 'team': 'Bal', 'active': 1, 'position': ['RP']},
	{'first_name': 'Erik', 'last_name': 'Bedard', 'rank': 165, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Matt', 'last_name': 'Belisle', 'rank': 166, 'team': 'Col', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brian', 'last_name': 'Fuentes', 'rank': 167, 'team': 'Oak', 'active': 1, 'position': ['RP']},
	{'first_name': 'Koji', 'last_name': 'Uehara', 'rank': 168, 'team': 'Bal', 'active': 1, 'position': ['RP']},
	{'first_name': 'Nelson', 'last_name': 'Figueroa', 'rank': 169, 'team': 'Hou', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Clayton', 'last_name': 'Richard', 'rank': 170, 'team': 'SD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Joe', 'last_name': 'Blanton', 'rank': 171, 'team': 'Phi', 'active': 1, 'position': ['SP']},
	{'first_name': 'Michael', 'last_name': 'Wuertz', 'rank': 172, 'team': 'Oak', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jordan', 'last_name': 'Walden', 'rank': 173, 'team': 'LAA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Matt', 'last_name': 'Reynolds', 'rank': 174, 'team': 'Col', 'active': 1, 'position': ['RP']},
	{'first_name': 'Edward', 'last_name': 'Mujica', 'rank': 175, 'team': 'Fla', 'active': 1, 'position': ['RP']},
	{'first_name': 'Peter', 'last_name': 'Moylan', 'rank': 176, 'team': 'Atl', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jason', 'last_name': 'Motte', 'rank': 177, 'team': 'StL', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brian', 'last_name': 'Sanches', 'rank': 178, 'team': 'Fla', 'active': 1, 'position': ['RP']},
	{'first_name': 'A.J.', 'last_name': 'Burnett', 'rank': 179, 'team': 'NYY', 'active': 1, 'position': ['SP']},
	{'first_name': 'Zach', 'last_name': 'Braddock', 'rank': 180, 'team': 'Mil', 'active': 1, 'position': ['RP']},
	{'first_name': 'Manny', 'last_name': 'Acosta', 'rank': 181, 'team': 'NYM', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mark', 'last_name': 'Buehrle', 'rank': 182, 'team': 'CWS', 'active': 1, 'position': ['SP']},
	{'first_name': 'Sean', 'last_name': 'Marshall', 'rank': 183, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Sean', 'last_name': 'Burnett', 'rank': 184, 'team': 'Was', 'active': 1, 'position': ['RP']},
	{'first_name': 'Dan', 'last_name': 'Wheeler', 'rank': 185, 'team': 'Bos', 'active': 1, 'position': ['RP']},
	{'first_name': 'Cory', 'last_name': 'Luebke', 'rank': 186, 'team': 'SD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeff', 'last_name': 'Niemann', 'rank': 187, 'team': 'TB', 'active': 1, 'position': ['SP']},
	{'first_name': 'Josh', 'last_name': 'Outman', 'rank': 188, 'team': 'Oak', 'active': 1, 'position': ['SP']},
	{'first_name': 'Darren', 'last_name': 'Oliver', 'rank': 189, 'team': 'Tex', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chris', 'last_name': 'Resop', 'rank': 190, 'team': 'Pit', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chris', 'last_name': 'Capuano', 'rank': 191, 'team': 'NYM', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'David', 'last_name': 'Hernandez', 'rank': 192, 'team': 'Ari', 'active': 1, 'position': ['RP', 'SP']},
	{'first_name': 'Ross', 'last_name': 'Ohlendorf', 'rank': 193, 'team': 'Pit', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tom', 'last_name': 'Gorzelanny', 'rank': 194, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kerry', 'last_name': 'Wood', 'rank': 195, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Marc', 'last_name': 'Rzepczynski', 'rank': 196, 'team': 'Tor', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jake', 'last_name': 'Arrieta', 'rank': 197, 'team': 'Bal', 'active': 1, 'position': ['SP']},
	{'first_name': 'David', 'last_name': 'Robertson', 'rank': 198, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'Bill', 'last_name': 'Bray', 'rank': 199, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Bobby', 'last_name': 'Jenks', 'rank': 200, 'team': 'Bos', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chris', 'last_name': 'Volstad', 'rank': 201, 'team': 'Fla', 'active': 1, 'position': ['SP']},
	{'first_name': 'Santiago', 'last_name': 'Casilla', 'rank': 202, 'team': 'SF', 'active': 1, 'position': ['RP']},
	{'first_name': 'Fausto', 'last_name': 'Carmona', 'rank': 203, 'team': 'Cle', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jesse', 'last_name': 'Crain', 'rank': 204, 'team': 'CWS', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brandon', 'last_name': 'Beachy', 'rank': 205, 'team': 'Atl', 'active': 1, 'position': ['SP']},
	{'first_name': 'Barry', 'last_name': 'Zito', 'rank': 206, 'team': 'SF', 'active': 1, 'position': ['SP']},
	{'first_name': 'Wilton', 'last_name': 'Lopez', 'rank': 207, 'team': 'Hou', 'active': 1, 'position': ['RP']},
	{'first_name': 'Joba', 'last_name': 'Chamberlain', 'rank': 208, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'Pat', 'last_name': 'Misch', 'rank': 209, 'team': 'NYM', 'active': 1, 'position': ['SP']},
	{'first_name': 'Dan', 'last_name': 'Runzler', 'rank': 210, 'team': 'SF', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mark', 'last_name': 'Melancon', 'rank': 211, 'team': 'Hou', 'active': 1, 'position': ['RP']},
	{'first_name': 'Scott', 'last_name': 'Mathieson', 'rank': 212, 'team': 'Phi', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chad', 'last_name': 'Qualls', 'rank': 213, 'team': 'SD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Carlos', 'last_name': 'Carrasco', 'rank': 214, 'team': 'Cle', 'active': 1, 'position': ['SP']},
	{'first_name': 'Doug', 'last_name': 'Slaten', 'rank': 215, 'team': 'Was', 'active': 1, 'position': ['RP']},
	{'first_name': 'Joe', 'last_name': 'Thatcher', 'rank': 216, 'team': 'SD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Burke', 'last_name': 'Badenhop', 'rank': 217, 'team': 'Fla', 'active': 1, 'position': ['RP']},
	{'first_name': 'D.J.', 'last_name': 'Carrasco', 'rank': 218, 'team': 'NYM', 'active': 1, 'position': ['RP']},
	{'first_name': 'Javier', 'last_name': 'Lopez', 'rank': 219, 'team': 'SF', 'active': 1, 'position': ['RP']},
	{'first_name': 'J.D.', 'last_name': 'Martin', 'rank': 220, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Ramon', 'last_name': 'Ramirez', 'rank': 221, 'team': 'SF', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jeremy', 'last_name': 'Affeldt', 'rank': 222, 'team': 'SF', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mike', 'last_name': 'Leake', 'rank': 223, 'team': 'Cin', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jose', 'last_name': 'Mijares', 'rank': 224, 'team': 'Min', 'active': 1, 'position': ['RP']},
	{'first_name': 'Justin', 'last_name': 'Duchscherer', 'rank': 225, 'team': 'Bal', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jose', 'last_name': 'Contreras', 'rank': 226, 'team': 'Phi', 'active': 1, 'position': ['RP']},
	{'first_name': 'Rich', 'last_name': 'Harden', 'rank': 227, 'team': 'Oak', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jason', 'last_name': 'Hammel', 'rank': 228, 'team': 'Col', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jenrry', 'last_name': 'Mejia', 'rank': 229, 'team': 'NYM', 'active': 1, 'position': ['RP']},
	{'first_name': 'Ernesto', 'last_name': 'Frieri', 'rank': 230, 'team': 'SD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chris', 'last_name': 'Tillman', 'rank': 231, 'team': 'Bal', 'active': 1, 'position': ['SP']},
	{'first_name': 'J.P.', 'last_name': 'Howell', 'rank': 232, 'team': 'TB', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chad', 'last_name': 'Durbin', 'rank': 233, 'team': 'FA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Homer', 'last_name': 'Bailey', 'rank': 234, 'team': 'Cin', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jared', 'last_name': 'Burton', 'rank': 235, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kyle', 'last_name': 'Farnsworth', 'rank': 236, 'team': 'TB', 'active': 1, 'position': ['RP']},
	{'first_name': 'Sergio', 'last_name': 'Mitre', 'rank': 237, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'Adam', 'last_name': 'Russell', 'rank': 238, 'team': 'TB', 'active': 1, 'position': ['RP']},
	{'first_name': 'LaTroy', 'last_name': 'Hawkins', 'rank': 239, 'team': 'Mil', 'active': 1, 'position': ['RP']},
	{'first_name': 'Josh', 'last_name': 'Tomlin', 'rank': 240, 'team': 'Cle', 'active': 1, 'position': ['SP']},
	{'first_name': 'Shawn', 'last_name': 'Camp', 'rank': 241, 'team': 'Tor', 'active': 1, 'position': ['RP']},
	{'first_name': 'Daisuke', 'last_name': 'Matsuzaka', 'rank': 242, 'team': 'Bos', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tanner', 'last_name': 'Scheppers', 'rank': 243, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'Gil', 'last_name': 'Meche', 'rank': 244, 'team': 'FA', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Jon', 'last_name': 'Rauch', 'rank': 245, 'team': 'Tor', 'active': 1, 'position': ['RP']},
	{'first_name': 'Ryan', 'last_name': 'Perry', 'rank': 246, 'team': 'Det', 'active': 1, 'position': ['RP']},
	{'first_name': 'Ryan', 'last_name': 'Webb', 'rank': 247, 'team': 'Fla', 'active': 1, 'position': ['RP']},
	{'first_name': 'Bud', 'last_name': 'Norris', 'rank': 248, 'team': 'Hou', 'active': 1, 'position': ['SP']},
	{'first_name': 'Fernando', 'last_name': 'Salas', 'rank': 249, 'team': 'StL', 'active': 1, 'position': ['RP']},
	{'first_name': 'Casey', 'last_name': 'Coleman', 'rank': 250, 'team': 'ChC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Angel', 'last_name': 'Guzman', 'rank': 251, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jason', 'last_name': 'Vargas', 'rank': 252, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Guillermo', 'last_name': 'Mota', 'rank': 253, 'team': 'SF', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mike', 'last_name': 'Minor', 'rank': 254, 'team': 'Atl', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeff', 'last_name': 'Francis', 'rank': 255, 'team': 'KC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Barry', 'last_name': 'Enright', 'rank': 256, 'team': 'Ari', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jonathon', 'last_name': 'Niese', 'rank': 257, 'team': 'NYM', 'active': 1, 'position': ['SP']},
	{'first_name': 'Sam', 'last_name': 'Demel', 'rank': 258, 'team': 'Ari', 'active': 1, 'position': ['RP']},
	{'first_name': 'Bobby', 'last_name': 'Cramer', 'rank': 259, 'team': 'Oak', 'active': 1, 'position': ['SP']},
	{'first_name': 'Scott', 'last_name': 'Linebrink', 'rank': 260, 'team': 'Atl', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brad', 'last_name': 'Bergesen', 'rank': 261, 'team': 'Bal', 'active': 1, 'position': ['SP']},
	{'first_name': 'Casey', 'last_name': 'Janssen', 'rank': 262, 'team': 'Tor', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jim', 'last_name': 'Johnson', 'rank': 263, 'team': 'Bal', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mike', 'last_name': 'Ekstrom', 'rank': 264, 'team': 'TB', 'active': 1, 'position': ['RP']},
	{'first_name': 'Joel', 'last_name': 'Zumaya', 'rank': 265, 'team': 'Det', 'active': 1, 'position': ['RP']},
	{'first_name': 'Dillon', 'last_name': 'Gee', 'rank': 266, 'team': 'NYM', 'active': 1, 'position': ['SP']},
	{'first_name': 'Joe', 'last_name': 'Saunders', 'rank': 267, 'team': 'Ari', 'active': 1, 'position': ['SP']},
	{'first_name': 'Trever', 'last_name': 'Miller', 'rank': 268, 'team': 'StL', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jose', 'last_name': 'Veras', 'rank': 269, 'team': 'Pit', 'active': 1, 'position': ['RP']},
	{'first_name': 'Robinson', 'last_name': 'Tejeda', 'rank': 270, 'team': 'KC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Marcos', 'last_name': 'Mateo', 'rank': 271, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Simon', 'last_name': 'Castro', 'rank': 272, 'team': 'SD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Andrew', 'last_name': 'Cashner', 'rank': 273, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Joey', 'last_name': 'Devine', 'rank': 274, 'team': 'Oak', 'active': 1, 'position': ['RP']},
	{'first_name': 'Eric', 'last_name': "O'Flaherty", 'rank': 275, 'team': 'Atl', 'active': 1, 'position': ['RP']},
	{'first_name': 'Tim', 'last_name': 'Collins', 'rank': 276, 'team': 'KC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jacob', 'last_name': 'Turner', 'rank': 277, 'team': 'Det', 'active': 1, 'position': ['SP']},
	{'first_name': 'Collin', 'last_name': 'Balester', 'rank': 278, 'team': 'Was', 'active': 1, 'position': ['RP']},
	{'first_name': 'Juan', 'last_name': 'Gutierrez', 'rank': 279, 'team': 'Ari', 'active': 1, 'position': ['RP']},
	{'first_name': 'Doug', 'last_name': 'Fister', 'rank': 280, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Anthony', 'last_name': 'Slama', 'rank': 281, 'team': 'Min', 'active': 1, 'position': ['RP']},
	{'first_name': 'Tommy', 'last_name': 'Hunter', 'rank': 282, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'John', 'last_name': 'Lannan', 'rank': 283, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tim', 'last_name': 'Byrdak', 'rank': 284, 'team': 'NYM', 'active': 1, 'position': ['RP']},
	{'first_name': 'Pat', 'last_name': 'Neshek', 'rank': 285, 'team': 'Min', 'active': 1, 'position': ['RP']},
	{'first_name': 'Elmer', 'last_name': 'Dessens', 'rank': 286, 'team': 'FA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kevin', 'last_name': 'Jepsen', 'rank': 287, 'team': 'LAA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Boone', 'last_name': 'Logan', 'rank': 288, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'Scott', 'last_name': 'Feldman', 'rank': 289, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'Romulo', 'last_name': 'Sanchez', 'rank': 290, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'Ramon', 'last_name': 'Troncoso', 'rank': 291, 'team': 'LAD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Pedro', 'last_name': 'Feliciano', 'rank': 292, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'Hideki', 'last_name': 'Okajima', 'rank': 293, 'team': 'Bos', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brad', 'last_name': 'Ziegler', 'rank': 294, 'team': 'Oak', 'active': 1, 'position': ['RP']},
	{'first_name': 'Fernando', 'last_name': 'Abad', 'rank': 295, 'team': 'Hou', 'active': 1, 'position': ['RP']},
	{'first_name': 'Ivan', 'last_name': 'Nova', 'rank': 296, 'team': 'NYY', 'active': 1, 'position': ['SP']},
	{'first_name': 'Felix', 'last_name': 'Doubront', 'rank': 297, 'team': 'Bos', 'active': 1, 'position': ['RP']},
	{'first_name': 'Michael', 'last_name': 'McClendon', 'rank': 298, 'team': 'Mil', 'active': 1, 'position': ['RP']},
	{'first_name': 'Dennys', 'last_name': 'Reyes', 'rank': 299, 'team': 'FA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brad', 'last_name': 'Mills', 'rank': 300, 'team': 'Tor', 'active': 1, 'position': ['RP']},
	{'first_name': 'Vinnie', 'last_name': 'Pestano', 'rank': 301, 'team': 'Cle', 'active': 1, 'position': ['RP']},
	{'first_name': 'Armando', 'last_name': 'Galarraga', 'rank': 302, 'team': 'Ari', 'active': 1, 'position': ['SP']},
	{'first_name': 'Scott', 'last_name': 'Richmond', 'rank': 303, 'team': 'Tor', 'active': 1, 'position': ['SP']},
	{'first_name': 'John', 'last_name': 'Ely', 'rank': 304, 'team': 'LAD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tony', 'last_name': 'Sipp', 'rank': 305, 'team': 'Cle', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jensen', 'last_name': 'Lewis', 'rank': 306, 'team': 'Cle', 'active': 1, 'position': ['RP']},
	{'first_name': 'Omar', 'last_name': 'Beltre', 'rank': 307, 'team': 'Tex', 'active': 1, 'position': ['RP']},
	{'first_name': 'Bobby', 'last_name': 'Parnell', 'rank': 308, 'team': 'NYM', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jose', 'last_name': 'Arredondo', 'rank': 309, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Rafael', 'last_name': 'Perez', 'rank': 310, 'team': 'Cle', 'active': 1, 'position': ['RP']},
	{'first_name': 'Casey', 'last_name': 'Kelly', 'rank': 311, 'team': 'SD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Sergio', 'last_name': 'Santos', 'rank': 312, 'team': 'CWS', 'active': 1, 'position': ['RP']},
	{'first_name': 'Frank', 'last_name': 'Herrmann', 'rank': 313, 'team': 'Cle', 'active': 1, 'position': ['RP']},
	{'first_name': 'Carlos', 'last_name': 'Fisher', 'rank': 314, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Andrew', 'last_name': 'Brackman', 'rank': 315, 'team': 'NYY', 'active': 1, 'position': ['RP']},
	{'first_name': 'Daniel', 'last_name': 'Schlereth', 'rank': 316, 'team': 'Det', 'active': 1, 'position': ['RP']},
	{'first_name': 'Carlos', 'last_name': 'Gutierrez', 'rank': 317, 'team': 'Min', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mauricio', 'last_name': 'Robles', 'rank': 318, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Will', 'last_name': 'Ohman', 'rank': 319, 'team': 'CWS', 'active': 1, 'position': ['RP']},
	{'first_name': 'Eric', 'last_name': 'Hurley', 'rank': 320, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'Craig', 'last_name': 'Stammen', 'rank': 321, 'team': 'Was', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Ronald', 'last_name': 'Belisario', 'rank': 322, 'team': 'LAD', 'active': 1, 'position': ['RP']},
	{'first_name': 'Joe', 'last_name': 'Smith', 'rank': 323, 'team': 'Cle', 'active': 1, 'position': ['RP']},
	{'first_name': 'Aaron', 'last_name': 'Heilman', 'rank': 324, 'team': 'Ari', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kyle', 'last_name': 'Kendrick', 'rank': 325, 'team': 'Phi', 'active': 1, 'position': ['SP']},
	{'first_name': 'Matt', 'last_name': 'Daley', 'rank': 326, 'team': 'Col', 'active': 1, 'position': ['RP']},
	{'first_name': 'Todd', 'last_name': 'Coffey', 'rank': 327, 'team': 'Was', 'active': 1, 'position': ['RP']},
	{'first_name': 'Zach', 'last_name': 'Stewart', 'rank': 328, 'team': 'FA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jason', 'last_name': 'Bulger', 'rank': 329, 'team': 'LAA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kenshin', 'last_name': 'Kawakami', 'rank': 330, 'team': 'Atl', 'active': 1, 'position': ['SP']},
	{'first_name': 'Justin', 'last_name': 'Masterson', 'rank': 331, 'team': 'Cle', 'active': 1, 'position': ['SP']},
	{'first_name': 'Matt', 'last_name': 'Maloney', 'rank': 332, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jesse', 'last_name': 'Litsch', 'rank': 333, 'team': 'Tor', 'active': 1, 'position': ['SP']},
	{'first_name': 'Alberto', 'last_name': 'Arias', 'rank': 334, 'team': 'Hou', 'active': 1, 'position': ['RP']},
	{'first_name': 'Matt', 'last_name': 'Harrison', 'rank': 335, 'team': 'Tex', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Tim', 'last_name': 'Wakefield', 'rank': 336, 'team': 'Bos', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Mike', 'last_name': 'Dunn', 'rank': 337, 'team': 'Fla', 'active': 1, 'position': ['RP']},
	{'first_name': 'Anthony', 'last_name': 'Reyes', 'rank': 338, 'team': 'Cle', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeremy', 'last_name': 'Jeffress', 'rank': 339, 'team': 'KC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Manny', 'last_name': 'Delcarmen', 'rank': 340, 'team': 'FA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Danny', 'last_name': 'Cortes', 'rank': 341, 'team': 'Sea', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kevin', 'last_name': 'Correia', 'rank': 342, 'team': 'Pit', 'active': 1, 'position': ['SP']},
	{'first_name': 'John', 'last_name': 'Grabow', 'rank': 343, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'J.C.', 'last_name': 'Romero', 'rank': 344, 'team': 'Phi', 'active': 1, 'position': ['RP']},
	{'first_name': 'Nick', 'last_name': 'Blackburn', 'rank': 345, 'team': 'Min', 'active': 1, 'position': ['SP']},
	{'first_name': 'Joe', 'last_name': 'Beimel', 'rank': 346, 'team': 'Pit', 'active': 1, 'position': ['RP']},
	{'first_name': 'Adalberto', 'last_name': 'Mendez', 'rank': 347, 'team': 'Fla', 'active': 1, 'position': ['SP']},
	{'first_name': 'Brandon', 'last_name': 'McCarthy', 'rank': 348, 'team': 'Oak', 'active': 1, 'position': ['SP']},
	{'first_name': 'Rick', 'last_name': 'VandenHurk', 'rank': 349, 'team': 'Bal', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kevin', 'last_name': 'Mulvey', 'rank': 350, 'team': 'Ari', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jason', 'last_name': 'Berken', 'rank': 351, 'team': 'Bal', 'active': 1, 'position': ['RP']},
	{'first_name': 'Luke', 'last_name': 'Hochevar', 'rank': 352, 'team': 'KC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Chaz', 'last_name': 'Roe', 'rank': 353, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tyson', 'last_name': 'Ross', 'rank': 354, 'team': 'Oak', 'active': 1, 'position': ['RP']},
	{'first_name': 'Trevor', 'last_name': 'Bell', 'rank': 355, 'team': 'LAA', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Dustin', 'last_name': 'McGowan', 'rank': 356, 'team': 'Tor', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeremy', 'last_name': 'Accardo', 'rank': 357, 'team': 'Bal', 'active': 1, 'position': ['RP']},
	{'first_name': 'Vin', 'last_name': 'Mazzaro', 'rank': 358, 'team': 'KC', 'active': 1, 'position': ['SP']},
	{'first_name': 'David', 'last_name': 'Huff', 'rank': 359, 'team': 'Cle', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeff', 'last_name': 'Fulchino', 'rank': 360, 'team': 'Hou', 'active': 1, 'position': ['RP']},
	{'first_name': 'Matt', 'last_name': 'Lindstrom', 'rank': 361, 'team': 'Col', 'active': 1, 'position': ['RP']},
	{'first_name': 'David', 'last_name': 'Pauley', 'rank': 362, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Aaron', 'last_name': 'Cook', 'rank': 363, 'team': 'Col', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jesse', 'last_name': 'Chavez', 'rank': 364, 'team': 'KC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Kevin', 'last_name': 'Pucetas', 'rank': 365, 'team': 'KC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Dave', 'last_name': 'Bush', 'rank': 366, 'team': 'Tex', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kam', 'last_name': 'Mickolio', 'rank': 367, 'team': 'Ari', 'active': 1, 'position': ['RP']},
	{'first_name': 'Clayton', 'last_name': 'Mortensen', 'rank': 368, 'team': 'Col', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jess', 'last_name': 'Todd', 'rank': 369, 'team': 'Cle', 'active': 1, 'position': ['RP']},
	{'first_name': 'Andrew', 'last_name': 'Oliver', 'rank': 370, 'team': 'Det', 'active': 1, 'position': ['SP']},
	{'first_name': 'Michael', 'last_name': 'Kirkman', 'rank': 371, 'team': 'Tex', 'active': 1, 'position': ['RP']},
	{'first_name': 'Wade', 'last_name': 'LeBlanc', 'rank': 372, 'team': 'SD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Greg', 'last_name': 'Holland', 'rank': 373, 'team': 'KC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Blake', 'last_name': 'Hawksworth', 'rank': 374, 'team': 'LAD', 'active': 1, 'position': ['RP', 'SP']},
	{'first_name': 'Charlie', 'last_name': 'Morton', 'rank': 375, 'team': 'Pit', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeremy', 'last_name': 'Bonderman', 'rank': 376, 'team': 'FA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Charlie', 'last_name': 'Haeger', 'rank': 377, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Franklin', 'last_name': 'Morales', 'rank': 378, 'team': 'Col', 'active': 1, 'position': ['RP']},
	{'first_name': 'Aaron', 'last_name': 'Crow', 'rank': 379, 'team': 'KC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Glen', 'last_name': 'Perkins', 'rank': 380, 'team': 'Min', 'active': 1, 'position': ['RP']},
	{'first_name': 'Scott', 'last_name': 'Kazmir', 'rank': 381, 'team': 'LAA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Esmil', 'last_name': 'Rogers', 'rank': 382, 'team': 'Col', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Troy', 'last_name': 'Patton', 'rank': 383, 'team': 'Bal', 'active': 1, 'position': ['RP']},
	{'first_name': 'Daniel', 'last_name': 'McCutchen', 'rank': 384, 'team': 'Pit', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Freddy', 'last_name': 'Garcia', 'rank': 385, 'team': 'FA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Mark', 'last_name': 'Lowe', 'rank': 386, 'team': 'Tex', 'active': 1, 'position': ['RP']},
	{'first_name': 'Mitchell', 'last_name': 'Boggs', 'rank': 387, 'team': 'StL', 'active': 1, 'position': ['RP']},
	{'first_name': 'George', 'last_name': 'Sherrill', 'rank': 388, 'team': 'Atl', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chris', 'last_name': 'Ray', 'rank': 389, 'team': 'Sea', 'active': 1, 'position': ['RP']},
	{'first_name': 'P.J.', 'last_name': 'Walters', 'rank': 390, 'team': 'StL', 'active': 1, 'position': ['RP']},
	{'first_name': 'Sean', 'last_name': 'West', 'rank': 391, 'team': 'Fla', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tony', 'last_name': 'Pena', 'rank': 392, 'team': 'CWS', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chien-Ming', 'last_name': 'Wang', 'rank': 393, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jorge', 'last_name': 'Sosa', 'rank': 394, 'team': 'FA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Chad', 'last_name': 'Cordero', 'rank': 395, 'team': 'Tor', 'active': 1, 'position': ['RP']},
	{'first_name': 'Andy', 'last_name': 'Sonnanstine', 'rank': 396, 'team': 'TB', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jeff', 'last_name': 'Karstens', 'rank': 397, 'team': 'Pit', 'active': 1, 'position': ['SP']},
	{'first_name': 'Luke', 'last_name': 'French', 'rank': 398, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Chad', 'last_name': 'Gaudin', 'rank': 399, 'team': 'Was', 'active': 1, 'position': ['RP']},
	{'first_name': 'Scott', 'last_name': 'Olsen', 'rank': 400, 'team': 'Pit', 'active': 1, 'position': ['SP']},
	{'first_name': 'Danys', 'last_name': 'Baez', 'rank': 401, 'team': 'Phi', 'active': 1, 'position': ['RP']},
	{'first_name': 'Felipe', 'last_name': 'Paulino', 'rank': 402, 'team': 'Col', 'active': 1, 'position': ['SP']},
	{'first_name': 'Blake', 'last_name': 'Wood', 'rank': 403, 'team': 'KC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jeff', 'last_name': 'Manship', 'rank': 404, 'team': 'Min', 'active': 1, 'position': ['RP']},
	{'first_name': 'Paul', 'last_name': 'Maholm', 'rank': 405, 'team': 'Pit', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kevin', 'last_name': 'Millwood', 'rank': 406, 'team': 'FA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Matt', 'last_name': 'Palmer', 'rank': 407, 'team': 'LAA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jason', 'last_name': 'Marquis', 'rank': 408, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Thomas', 'last_name': 'Diamond', 'rank': 409, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Brian', 'last_name': 'Tallet', 'rank': 410, 'team': 'StL', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Wesley', 'last_name': 'Wright', 'rank': 411, 'team': 'Hou', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jeanmar', 'last_name': 'Gomez', 'rank': 412, 'team': 'Cle', 'active': 1, 'position': ['SP']},
	{'first_name': 'Andrew', 'last_name': 'Miller', 'rank': 413, 'team': 'Bos', 'active': 1, 'position': ['SP']},
	{'first_name': 'Sean', 'last_name': "O'Sullivan", 'rank': 414, 'team': 'KC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Aaron', 'last_name': 'Laffey', 'rank': 415, 'team': 'Cle', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Ryan', 'last_name': 'Rowland-Smith', 'rank': 416, 'team': 'Hou', 'active': 1, 'position': ['SP']},
	{'first_name': 'Livan', 'last_name': 'Hernandez', 'rank': 417, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Luis', 'last_name': 'Atilano', 'rank': 418, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Manny', 'last_name': 'Parra', 'rank': 419, 'team': 'Mil', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Jordan', 'last_name': 'Smith', 'rank': 420, 'team': 'Cin', 'active': 1, 'position': ['RP']},
	{'first_name': 'Dustin', 'last_name': 'Moseley', 'rank': 421, 'team': 'SD', 'active': 1, 'position': ['SP']},
	{'first_name': 'Lucas', 'last_name': 'Harrell', 'rank': 422, 'team': 'CWS', 'active': 1, 'position': ['RP']},
	{'first_name': 'Rodrigo', 'last_name': 'Lopez', 'rank': 423, 'team': 'Atl', 'active': 1, 'position': ['SP']},
	{'first_name': 'Mitch', 'last_name': 'Talbot', 'rank': 424, 'team': 'Cle', 'active': 1, 'position': ['SP']},
	{'first_name': 'Carlos', 'last_name': 'Silva', 'rank': 425, 'team': 'ChC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Oliver', 'last_name': 'Perez', 'rank': 426, 'team': 'NYM', 'active': 1, 'position': ['SP', 'RP']},
	{'first_name': 'Kyle', 'last_name': 'Davies', 'rank': 427, 'team': 'KC', 'active': 1, 'position': ['SP']},
	{'first_name': 'Sean', 'last_name': 'Gallagher', 'rank': 428, 'team': 'Pit', 'active': 1, 'position': ['RP']},
	{'first_name': 'Zach', 'last_name': 'Duke', 'rank': 429, 'team': 'Ari', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kyle', 'last_name': 'Lohse', 'rank': 430, 'team': 'StL', 'active': 1, 'position': ['SP']},
	{'first_name': 'Eddie', 'last_name': 'Bonine', 'rank': 431, 'team': 'Phi', 'active': 1, 'position': ['RP']},
	{'first_name': 'Ross', 'last_name': 'Detwiler', 'rank': 432, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeff', 'last_name': 'Samardzija', 'rank': 433, 'team': 'ChC', 'active': 1, 'position': ['RP']},
	{'first_name': 'Nate', 'last_name': 'Robertson', 'rank': 434, 'team': 'Sea', 'active': 1, 'position': ['SP']},
	{'first_name': 'Yunesky', 'last_name': 'Maya', 'rank': 435, 'team': 'Was', 'active': 1, 'position': ['SP']},
	{'first_name': 'David', 'last_name': 'Herndon', 'rank': 436, 'team': 'Phi', 'active': 1, 'position': ['RP']},
	{'first_name': 'Trevor', 'last_name': 'Hoffman', 'rank': 437, 'team': 'FA', 'active': 1, 'position': ['RP']},
	{'first_name': 'Jamie', 'last_name': 'Moyer', 'rank': 438, 'team': 'FA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Kenny', 'last_name': 'Rogers', 'rank': 439, 'team': 'FA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Tom', 'last_name': 'Glavine', 'rank': 440, 'team': 'FA', 'active': 1, 'position': ['SP']},
	{'first_name': 'Jeff', 'last_name': 'Mathis', 'rank': 441, 'team': 'LAA', 'active': 1, 'position': ['C']},
	{'first_name': 'Hank', 'last_name': 'Conger', 'rank': 442, 'team': 'LAA', 'active': 1, 'position': ['C']}
];

setTimeout(function(){
    db.populate('mlb_players', mlb_players, function(err,docs){
        console.log('Cleared and added ' + docs.length + ' MLB players');
    });
}, 2000);
