var db = require('../lib/mongo').db;

var nba_players = [
    {'first_name': 'Kevin', 'last_name': 'Durant', 'rank': 1, 'team': 'OKC', 'active': 1, 'position': ['SF']},
    {'first_name': 'Chris', 'last_name': 'Paul', 'rank': 2, 'team': 'Nor', 'active': 1, 'position': ['PG']},
    {'first_name': 'LeBron', 'last_name': 'James', 'rank': 3, 'team': 'Mia', 'active': 1, 'position': ['SF']},
    {'first_name': 'Dirk', 'last_name': 'Nowitzki', 'rank': 4, 'team': 'Dal', 'active': 1, 'position': ['PF']},
    {'first_name': 'Kobe', 'last_name': 'Bryant', 'rank': 5, 'team': 'LAL', 'active': 1, 'position': ['SG']},
    {'first_name': 'Dwyane', 'last_name': 'Wade', 'rank': 6, 'team': 'Mia', 'active': 1, 'position': ['SG']},
    {'first_name': 'Danny', 'last_name': 'Granger', 'rank': 7, 'team': 'Ind', 'active': 1, 'position': ['SF']},
    {'first_name': 'Deron', 'last_name': 'Williams', 'rank': 8, 'team': 'Uta', 'active': 1, 'position': ['PG']},
    {'first_name': 'Stephen', 'last_name': 'Curry', 'rank': 9, 'team': 'GS', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Dwight', 'last_name': 'Howard', 'rank': 10, 'team': 'Orl', 'active': 1, 'position': ['C']},
    {'first_name': 'Steve', 'last_name': 'Nash', 'rank': 11, 'team': 'Pho', 'active': 1, 'position': ['PG']},
    {'first_name': 'Pau', 'last_name': 'Gasol', 'rank': 12, 'team': 'LAL', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Jason', 'last_name': 'Kidd', 'rank': 13, 'team': 'Dal', 'active': 1, 'position': ['PG']},
    {'first_name': 'David', 'last_name': 'Lee', 'rank': 14, 'team': 'GS', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Brook', 'last_name': 'Lopez', 'rank': 15, 'team': 'NJ', 'active': 1, 'position': ['C']},
    {'first_name': 'Carmelo', 'last_name': 'Anthony', 'rank': 16, 'team': 'Den', 'active': 1, 'position': ['SF']},
    {'first_name': 'Amare', 'last_name': 'Stoudemire', 'rank': 17, 'team': 'NY', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Chauncey', 'last_name': 'Billups', 'rank': 18, 'team': 'Den', 'active': 1, 'position': ['PG']},
    {'first_name': 'Andre', 'last_name': 'Iguodala', 'rank': 19, 'team': 'Phi', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Gerald', 'last_name': 'Wallace', 'rank': 20, 'team': 'Cha', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Monta', 'last_name': 'Ellis', 'rank': 21, 'team': 'GS', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Chris', 'last_name': 'Bosh', 'rank': 22, 'team': 'Mia', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Brandon', 'last_name': 'Roy', 'rank': 23, 'team': 'Por', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Rajon', 'last_name': 'Rondo', 'rank': 24, 'team': 'Bos', 'active': 1, 'position': ['PG']},
    {'first_name': 'Josh', 'last_name': 'Smith', 'rank': 25, 'team': 'Atl', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Joe', 'last_name': 'Johnson', 'rank': 26, 'team': 'Atl', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Paul', 'last_name': 'Pierce', 'rank': 27, 'team': 'Bos', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Tyreke', 'last_name': 'Evans', 'rank': 28, 'team': 'Sac', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Tim', 'last_name': 'Duncan', 'rank': 29, 'team': 'SA', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Al', 'last_name': 'Jefferson', 'rank': 30, 'team': 'Uta', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Troy', 'last_name': 'Murphy', 'rank': 31, 'team': 'NJ', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'David', 'last_name': 'West', 'rank': 32, 'team': 'Nor', 'active': 1, 'position': ['PF']},
    {'first_name': 'Al', 'last_name': 'Horford', 'rank': 33, 'team': 'Atl', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Aaron', 'last_name': 'Brooks', 'rank': 34, 'team': 'Hou', 'active': 1, 'position': ['PG']},
    {'first_name': 'Carlos', 'last_name': 'Boozer', 'rank': 35, 'team': 'Chi', 'active': 1, 'position': ['PF']},
    {'first_name': 'Russell', 'last_name': 'Westbrook', 'rank': 36, 'team': 'OKC', 'active': 1, 'position': ['PG']},
    {'first_name': 'Darren', 'last_name': 'Collison', 'rank': 37, 'team': 'Ind', 'active': 1, 'position': ['PG']},
    {'first_name': 'Andrea', 'last_name': 'Bargnani', 'rank': 38, 'team': 'Tor', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Devin', 'last_name': 'Harris', 'rank': 39, 'team': 'NJ', 'active': 1, 'position': ['PG']},
    {'first_name': 'Stephen', 'last_name': 'Jackson', 'rank': 40, 'team': 'Cha', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Mo', 'last_name': 'Williams', 'rank': 41, 'team': 'Cle', 'active': 1, 'position': ['PG']},
    {'first_name': 'Rudy', 'last_name': 'Gay', 'rank': 42, 'team': 'Mem', 'active': 1, 'position': ['SF']},
    {'first_name': 'O.J.', 'last_name': 'Mayo', 'rank': 43, 'team': 'Mem', 'active': 1, 'position': ['SG']},
    {'first_name': 'Baron', 'last_name': 'Davis', 'rank': 44, 'team': 'LAC', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jason', 'last_name': 'Richardson', 'rank': 45, 'team': 'Pho', 'active': 1, 'position': ['SG']},
    {'first_name': 'Joakim', 'last_name': 'Noah', 'rank': 46, 'team': 'Chi', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Marcus', 'last_name': 'Camby', 'rank': 47, 'team': 'Por', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Marc', 'last_name': 'Gasol', 'rank': 48, 'team': 'Mem', 'active': 1, 'position': ['C']},
    {'first_name': 'Zach', 'last_name': 'Randolph', 'rank': 49, 'team': 'Mem', 'active': 1, 'position': ['PF']},
    {'first_name': 'Antawn', 'last_name': 'Jamison', 'rank': 50, 'team': 'Cle', 'active': 1, 'position': ['PF']},
    {'first_name': 'Danilo', 'last_name': 'Gallinari', 'rank': 51, 'team': 'NY', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Raymond', 'last_name': 'Felton', 'rank': 52, 'team': 'NY', 'active': 1, 'position': ['PG']},
    {'first_name': 'Gilbert', 'last_name': 'Arenas', 'rank': 53, 'team': 'Was', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jeff', 'last_name': 'Green', 'rank': 54, 'team': 'OKC', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Rashard', 'last_name': 'Lewis', 'rank': 55, 'team': 'Orl', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Derrick', 'last_name': 'Rose', 'rank': 56, 'team': 'Chi', 'active': 1, 'position': ['PG']},
    {'first_name': 'John', 'last_name': 'Wall', 'rank': 57, 'team': 'Was', 'active': 1, 'position': ['PG']},
    {'first_name': 'Manu', 'last_name': 'Ginobili', 'rank': 58, 'team': 'SA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Brandon', 'last_name': 'Jennings', 'rank': 59, 'team': 'Mil', 'active': 1, 'position': ['PG']},
    {'first_name': 'Nene', 'last_name': 'Hilario', 'rank': 60, 'team': 'Den', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Andray', 'last_name': 'Blatche', 'rank': 61, 'team': 'Was', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Paul', 'last_name': 'Millsap', 'rank': 62, 'team': 'Uta', 'active': 1, 'position': ['PF']},
    {'first_name': 'Luis', 'last_name': 'Scola', 'rank': 63, 'team': 'Hou', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Kevin', 'last_name': 'Love', 'rank': 64, 'team': 'Min', 'active': 1, 'position': ['PF']},
    {'first_name': 'Eric', 'last_name': 'Gordon', 'rank': 65, 'team': 'LAC', 'active': 1, 'position': ['SG']},
    {'first_name': 'LaMarcus', 'last_name': 'Aldridge', 'rank': 66, 'team': 'Por', 'active': 1, 'position': ['PF']},
    {'first_name': 'Hedo', 'last_name': 'Turkoglu', 'rank': 67, 'team': 'Pho', 'active': 1, 'position': ['SF']},
    {'first_name': 'Andrew', 'last_name': 'Bogut', 'rank': 68, 'team': 'Mil', 'active': 1, 'position': ['C']},
    {'first_name': 'Anthony', 'last_name': 'Randolph', 'rank': 69, 'team': 'NY', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Jrue', 'last_name': 'Holiday', 'rank': 70, 'team': 'Phi', 'active': 1, 'position': ['PG']},
    {'first_name': 'Trevor', 'last_name': 'Ariza', 'rank': 71, 'team': 'Nor', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Caron', 'last_name': 'Butler', 'rank': 72, 'team': 'Dal', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Ray', 'last_name': 'Allen', 'rank': 73, 'team': 'Bos', 'active': 1, 'position': ['SG']},
    {'first_name': 'Chris', 'last_name': 'Kaman', 'rank': 74, 'team': 'LAC', 'active': 1, 'position': ['C']},
    {'first_name': 'Kevin', 'last_name': 'Garnett', 'rank': 75, 'team': 'Bos', 'active': 1, 'position': ['PF']},
    {'first_name': 'Tony', 'last_name': 'Parker', 'rank': 76, 'team': 'SA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Kevin', 'last_name': 'Martin', 'rank': 77, 'team': 'Hou', 'active': 1, 'position': ['SG']},
    {'first_name': 'Vince', 'last_name': 'Carter', 'rank': 78, 'team': 'Orl', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Jason', 'last_name': 'Terry', 'rank': 79, 'team': 'Dal', 'active': 1, 'position': ['SG']},
    {'first_name': 'Luol', 'last_name': 'Deng', 'rank': 80, 'team': 'Chi', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jamal', 'last_name': 'Crawford', 'rank': 81, 'team': 'Atl', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'Marcus', 'last_name': 'Thornton', 'rank': 82, 'team': 'Nor', 'active': 1, 'position': ['SG']},
    {'first_name': 'Andrew', 'last_name': 'Bynum', 'rank': 83, 'team': 'LAL', 'active': 1, 'position': ['C']},
    {'first_name': 'Lamar', 'last_name': 'Odom', 'rank': 84, 'team': 'LAL', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Roy', 'last_name': 'Hibbert', 'rank': 85, 'team': 'Ind', 'active': 1, 'position': ['C']},
    {'first_name': 'Leandro', 'last_name': 'Barbosa', 'rank': 86, 'team': 'Tor', 'active': 1, 'position': ['SG']},
    {'first_name': 'Blake', 'last_name': 'Griffin', 'rank': 87, 'team': 'LAC', 'active': 1, 'position': ['PF']},
    {'first_name': 'John', 'last_name': 'Salmons', 'rank': 88, 'team': 'Mil', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Michael', 'last_name': 'Beasley', 'rank': 89, 'team': 'Min', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Samuel', 'last_name': 'Dalembert', 'rank': 90, 'team': 'Sac', 'active': 1, 'position': ['C']},
    {'first_name': 'Andre', 'last_name': 'Miller', 'rank': 91, 'team': 'Por', 'active': 1, 'position': ['PG']},
    {'first_name': 'Emeka', 'last_name': 'Okafor', 'rank': 92, 'team': 'Nor', 'active': 1, 'position': ['C']},
    {'first_name': 'Mike', 'last_name': 'Miller', 'rank': 93, 'team': 'Mia', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Andrei', 'last_name': 'Kirilenko', 'rank': 94, 'team': 'Uta', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Mike', 'last_name': 'Conley', 'rank': 95, 'team': 'Mem', 'active': 1, 'position': ['PG']},
    {'first_name': 'Rodney', 'last_name': 'Stuckey', 'rank': 96, 'team': 'Det', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Al', 'last_name': 'Harrington', 'rank': 97, 'team': 'Den', 'active': 1, 'position': ['PF']},
    {'first_name': 'Boris', 'last_name': 'Diaw', 'rank': 98, 'team': 'Cha', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Terrence', 'last_name': 'Williams', 'rank': 99, 'team': 'NJ', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Ben', 'last_name': 'Gordon', 'rank': 100, 'team': 'Det', 'active': 1, 'position': ['SG']},
    {'first_name': 'Jose', 'last_name': 'Calderon', 'rank': 101, 'team': 'Tor', 'active': 1, 'position': ['PG']},
    {'first_name': 'J.R.', 'last_name': 'Smith', 'rank': 102, 'team': 'Den', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Tyrus', 'last_name': 'Thomas', 'rank': 103, 'team': 'Cha', 'active': 1, 'position': ['PF']},
    {'first_name': 'Corey', 'last_name': 'Maggette', 'rank': 104, 'team': 'Mil', 'active': 1, 'position': ['SF']},
    {'first_name': 'Carl', 'last_name': 'Landry', 'rank': 105, 'team': 'Sac', 'active': 1, 'position': ['PF']},
    {'first_name': 'Elton', 'last_name': 'Brand', 'rank': 106, 'team': 'Phi', 'active': 1, 'position': ['PF']},
    {'first_name': 'Yao', 'last_name': 'Ming', 'rank': 107, 'team': 'Hou', 'active': 1, 'position': ['C']},
    {'first_name': 'Anderson', 'last_name': 'Varejao', 'rank': 108, 'team': 'Cle', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Nicolas', 'last_name': 'Batum', 'rank': 109, 'team': 'Por', 'active': 1, 'position': ['SF']},
    {'first_name': 'Wilson', 'last_name': 'Chandler', 'rank': 110, 'team': 'NY', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'J.J.', 'last_name': 'Hickson', 'rank': 111, 'team': 'Cle', 'active': 1, 'position': ['PF']},
    {'first_name': 'JaVale', 'last_name': 'McGee', 'rank': 112, 'team': 'Was', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Thaddeus', 'last_name': 'Young', 'rank': 113, 'team': 'Phi', 'active': 1, 'position': ['SF']},
    {'first_name': 'Kenyon', 'last_name': 'Martin', 'rank': 114, 'team': 'Den', 'active': 1, 'position': ['PF']},
    {'first_name': 'Serge', 'last_name': 'Ibaka', 'rank': 115, 'team': 'OKC', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Robin', 'last_name': 'Lopez', 'rank': 116, 'team': 'Pho', 'active': 1, 'position': ['C']},
    {'first_name': 'DeMarcus', 'last_name': 'Cousins', 'rank': 117, 'team': 'Sac', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Beno', 'last_name': 'Udrih', 'rank': 118, 'team': 'Sac', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Ron', 'last_name': 'Artest', 'rank': 119, 'team': 'LAL', 'active': 1, 'position': ['SF']},
    {'first_name': 'Andris', 'last_name': 'Biedrins', 'rank': 120, 'team': 'GS', 'active': 1, 'position': ['C']},
    {'first_name': 'Richard', 'last_name': 'Hamilton', 'rank': 121, 'team': 'Det', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Wesley', 'last_name': 'Johnson', 'rank': 122, 'team': 'Min', 'active': 1, 'position': ['SF']},
    {'first_name': 'Channing', 'last_name': 'Frye', 'rank': 123, 'team': 'Pho', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'James', 'last_name': 'Harden', 'rank': 124, 'team': 'OKC', 'active': 1, 'position': ['SG']},
    {'first_name': 'Lou', 'last_name': 'Williams', 'rank': 125, 'team': 'Phi', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Anthony', 'last_name': 'Morrow', 'rank': 126, 'team': 'NJ', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Jarrett', 'last_name': 'Jack', 'rank': 127, 'team': 'Tor', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Charlie', 'last_name': 'Villanueva', 'rank': 128, 'team': 'Det', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Greg', 'last_name': 'Oden', 'rank': 129, 'team': 'Por', 'active': 1, 'position': ['C']},
    {'first_name': 'Brad', 'last_name': 'Miller', 'rank': 130, 'team': 'Hou', 'active': 1, 'position': ['C']},
    {'first_name': 'Chris', 'last_name': 'Andersen', 'rank': 131, 'team': 'Den', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Jonny', 'last_name': 'Flynn', 'rank': 132, 'team': 'Min', 'active': 1, 'position': ['PG']},
    {'first_name': 'Josh', 'last_name': 'Howard', 'rank': 133, 'team': 'Was', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Spencer', 'last_name': 'Hawes', 'rank': 134, 'team': 'Phi', 'active': 1, 'position': ['C']},
    {'first_name': 'Jameer', 'last_name': 'Nelson', 'rank': 135, 'team': 'Orl', 'active': 1, 'position': ['PG']},
    {'first_name': 'Carlos', 'last_name': 'Delfino', 'rank': 136, 'team': 'Mil', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Evan', 'last_name': 'Turner', 'rank': 137, 'team': 'Phi', 'active': 1, 'position': ['SG']},
    {'first_name': 'Linas', 'last_name': 'Kleiza', 'rank': 138, 'team': 'Tor', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Tiago', 'last_name': 'Splitter', 'rank': 139, 'team': 'SA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Josh', 'last_name': 'Childress', 'rank': 140, 'team': 'Pho', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Shawn', 'last_name': 'Marion', 'rank': 141, 'team': 'Dal', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'George', 'last_name': 'Hill', 'rank': 142, 'team': 'SA', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Wesley', 'last_name': 'Matthews', 'rank': 143, 'team': 'Por', 'active': 1, 'position': ['SG']},
    {'first_name': 'Tayshaun', 'last_name': 'Prince', 'rank': 144, 'team': 'Det', 'active': 1, 'position': ['SF']},
    {'first_name': 'Marvin', 'last_name': 'Williams', 'rank': 145, 'team': 'Atl', 'active': 1, 'position': ['SF']},
    {'first_name': 'Shane', 'last_name': 'Battier', 'rank': 146, 'team': 'Hou', 'active': 1, 'position': ['SF']},
    {'first_name': 'Luke', 'last_name': 'Ridnour', 'rank': 147, 'team': 'Min', 'active': 1, 'position': ['PG']},
    {'first_name': 'Brandon', 'last_name': 'Rush', 'rank': 148, 'team': 'Ind', 'active': 1, 'position': ['SG']},
    {'first_name': 'Dorell', 'last_name': 'Wright', 'rank': 149, 'team': 'GS', 'active': 1, 'position': ['SF']},
    {'first_name': 'Reggie', 'last_name': 'Williams', 'rank': 150, 'team': 'GS', 'active': 1, 'position': ['SF']},
    {'first_name': 'Mike', 'last_name': 'Bibby', 'rank': 151, 'team': 'Atl', 'active': 1, 'position': ['PG']},
    {'first_name': 'Rodrigue', 'last_name': 'Beaubois', 'rank': 152, 'team': 'Dal', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Matt', 'last_name': 'Barnes', 'rank': 153, 'team': 'LAL', 'active': 1, 'position': ['SF']},
    {'first_name': 'Corey', 'last_name': 'Brewer', 'rank': 154, 'team': 'Min', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Jason', 'last_name': 'Thompson', 'rank': 155, 'team': 'Sac', 'active': 1, 'position': ['PF']},
    {'first_name': 'Martell', 'last_name': 'Webster', 'rank': 156, 'team': 'Min', 'active': 1, 'position': ['SF']},
    {'first_name': 'Grant', 'last_name': 'Hill', 'rank': 157, 'team': 'Pho', 'active': 1, 'position': ['SF']},
    {'first_name': 'Amir', 'last_name': 'Johnson', 'rank': 158, 'team': 'Tor', 'active': 1, 'position': ['PF']},
    {'first_name': 'Mehmet', 'last_name': 'Okur', 'rank': 159, 'team': 'Uta', 'active': 1, 'position': ['C']},
    {'first_name': 'Darko', 'last_name': 'Milicic', 'rank': 160, 'team': 'Min', 'active': 1, 'position': ['C']},
    {'first_name': 'Ersan', 'last_name': 'Ilyasova', 'rank': 161, 'team': 'Mil', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'DeJuan', 'last_name': 'Blair', 'rank': 162, 'team': 'SA', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Derrick', 'last_name': 'Favors', 'rank': 163, 'team': 'NJ', 'active': 1, 'position': ['PF']},
    {'first_name': 'Richard', 'last_name': 'Jefferson', 'rank': 164, 'team': 'SA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jamario', 'last_name': 'Moon', 'rank': 165, 'team': 'Cle', 'active': 1, 'position': ['SF']},
    {'first_name': 'Drew', 'last_name': 'Gooden', 'rank': 166, 'team': 'Mil', 'active': 1, 'position': ['PF']},
    {'first_name': 'Anthony', 'last_name': 'Tolliver', 'rank': 167, 'team': 'Min', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Kirk', 'last_name': 'Hinrich', 'rank': 168, 'team': 'Was', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'Kelenna', 'last_name': 'Azubuike', 'rank': 169, 'team': 'NY', 'active': 1, 'position': ['SF']},
    {'first_name': 'C.J.', 'last_name': 'Miles', 'rank': 170, 'team': 'Uta', 'active': 1, 'position': ['SF']},
    {'first_name': 'D.J.', 'last_name': 'Augustin', 'rank': 171, 'team': 'Cha', 'active': 1, 'position': ['PG']},
    {'first_name': 'Brendan', 'last_name': 'Haywood', 'rank': 172, 'team': 'Dal', 'active': 1, 'position': ['C']},
    {'first_name': 'Nate', 'last_name': 'Robinson', 'rank': 173, 'team': 'Bos', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Mike', 'last_name': 'Dunleavy', 'rank': 174, 'team': 'Ind', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Ty', 'last_name': 'Lawson', 'rank': 175, 'team': 'Den', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jermaine', 'last_name': "O'Neal", 'rank': 176, 'team': 'Bos', 'active': 1, 'position': ['C']},
    {'first_name': 'Shaun', 'last_name': 'Livingston', 'rank': 177, 'team': 'Cha', 'active': 1, 'position': ['PG']},
    {'first_name': 'Courtney', 'last_name': 'Lee', 'rank': 178, 'team': 'Hou', 'active': 1, 'position': ['SG']},
    {'first_name': 'Derek', 'last_name': 'Fisher', 'rank': 179, 'team': 'LAL', 'active': 1, 'position': ['PG']},
    {'first_name': 'Ronnie', 'last_name': 'Brewer', 'rank': 180, 'team': 'Chi', 'active': 1, 'position': ['SG']},
    {'first_name': 'Tyson', 'last_name': 'Chandler', 'rank': 181, 'team': 'Dal', 'active': 1, 'position': ['C']},
    {'first_name': 'Francisco', 'last_name': 'Garcia', 'rank': 182, 'team': 'Sac', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Rasual', 'last_name': 'Butler', 'rank': 183, 'team': 'LAC', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Tracy', 'last_name': 'McGrady', 'rank': 184, 'team': 'Det', 'active': 1, 'position': ['SG']},
    {'first_name': 'Omri', 'last_name': 'Casspi', 'rank': 185, 'team': 'Sac', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Thabo', 'last_name': 'Sefolosha', 'rank': 186, 'team': 'OKC', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Kyle', 'last_name': 'Lowry', 'rank': 187, 'team': 'Hou', 'active': 1, 'position': ['PG']},
    {'first_name': 'Arron', 'last_name': 'Afflalo', 'rank': 188, 'team': 'Den', 'active': 1, 'position': ['SG']},
    {'first_name': 'Travis', 'last_name': 'Outlaw', 'rank': 189, 'team': 'NJ', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Taj', 'last_name': 'Gibson', 'rank': 190, 'team': 'Chi', 'active': 1, 'position': ['PF']},
    {'first_name': 'Ed', 'last_name': 'Davis', 'rank': 191, 'team': 'Tor', 'active': 1, 'position': ['PF']},
    {'first_name': 'Julian', 'last_name': 'Wright', 'rank': 192, 'team': 'Tor', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Hakim', 'last_name': 'Warrick', 'rank': 193, 'team': 'Pho', 'active': 1, 'position': ['PF']},
    {'first_name': 'DeMar', 'last_name': 'DeRozan', 'rank': 194, 'team': 'Tor', 'active': 1, 'position': ['SG']},
    {'first_name': 'Brandan', 'last_name': 'Wright', 'rank': 195, 'team': 'GS', 'active': 1, 'position': ['PF']},
    {'first_name': 'Ramon', 'last_name': 'Sessions', 'rank': 196, 'team': 'Cle', 'active': 1, 'position': ['PG']},
    {'first_name': 'Michael', 'last_name': 'Redd', 'rank': 197, 'team': 'Mil', 'active': 1, 'position': ['SG']},
    {'first_name': 'Jared', 'last_name': 'Dudley', 'rank': 198, 'team': 'Pho', 'active': 1, 'position': ['SF']},
    {'first_name': 'Greg', 'last_name': 'Monroe', 'rank': 199, 'team': 'Det', 'active': 1, 'position': ['PF']},
    {'first_name': 'Yi', 'last_name': 'Jianlian', 'rank': 200, 'team': 'Was', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Shaquille', 'last_name': "O'Neal", 'rank': 201, 'team': 'Bos', 'active': 1, 'position': ['C']},
    {'first_name': 'Chase', 'last_name': 'Budinger', 'rank': 202, 'team': 'Hou', 'active': 1, 'position': ['SF']},
    {'first_name': 'C.J.', 'last_name': 'Watson', 'rank': 203, 'team': 'Chi', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Marreese', 'last_name': 'Speights', 'rank': 204, 'team': 'Phi', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Anthony', 'last_name': 'Parker', 'rank': 205, 'team': 'Cle', 'active': 1, 'position': ['SG']},
    {'first_name': 'Jonas', 'last_name': 'Jerebko', 'rank': 206, 'team': 'Det', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Ryan', 'last_name': 'Gomes', 'rank': 207, 'team': 'LAC', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Quentin', 'last_name': 'Richardson', 'rank': 208, 'team': 'Orl', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Udonis', 'last_name': 'Haslem', 'rank': 209, 'team': 'Mia', 'active': 1, 'position': ['PF']},
    {'first_name': 'Raja', 'last_name': 'Bell', 'rank': 210, 'team': 'Uta', 'active': 1, 'position': ['SG']},
    {'first_name': 'Goran', 'last_name': 'Dragic', 'rank': 211, 'team': 'Pho', 'active': 1, 'position': ['PG']},
    {'first_name': 'Mickael', 'last_name': 'Pietrus', 'rank': 212, 'team': 'Orl', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Nick', 'last_name': 'Collison', 'rank': 213, 'team': 'OKC', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'J.J.', 'last_name': 'Redick', 'rank': 214, 'team': 'Orl', 'active': 1, 'position': ['SG']},
    {'first_name': 'T.J.', 'last_name': 'Ford', 'rank': 215, 'team': 'Ind', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jason', 'last_name': 'Williams', 'rank': 216, 'team': 'Orl', 'active': 1, 'position': ['PG']},
    {'first_name': 'Bill', 'last_name': 'Walker', 'rank': 217, 'team': 'NY', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Toney', 'last_name': 'Douglas', 'rank': 218, 'team': 'NY', 'active': 1, 'position': ['PG']},
    {'first_name': 'Randy', 'last_name': 'Foye', 'rank': 219, 'team': 'LAC', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'Roger', 'last_name': 'Mason', 'rank': 220, 'team': 'NY', 'active': 1, 'position': ['SG']},
    {'first_name': 'Al-Farouq', 'last_name': 'Aminu', 'rank': 221, 'team': 'LAC', 'active': 1, 'position': ['SF']},
    {'first_name': 'Glen', 'last_name': 'Davis', 'rank': 222, 'team': 'Bos', 'active': 1, 'position': ['PF']},
    {'first_name': 'Al', 'last_name': 'Thornton', 'rank': 223, 'team': 'Was', 'active': 1, 'position': ['SF']},
    {'first_name': 'Andres', 'last_name': 'Nocioni', 'rank': 224, 'team': 'Phi', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Erick', 'last_name': 'Dampier', 'rank': 225, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Zydrunas', 'last_name': 'Ilgauskas', 'rank': 226, 'team': 'Mia', 'active': 1, 'position': ['C']},
    {'first_name': 'James', 'last_name': 'Posey', 'rank': 227, 'team': 'Ind', 'active': 1, 'position': ['SF']},
    {'first_name': 'Rudy', 'last_name': 'Fernandez', 'rank': 228, 'team': 'Por', 'active': 1, 'position': ['SG']},
    {'first_name': 'Luc', 'last_name': 'Richard', 'rank': 229, 'team': 'Mil', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Steve', 'last_name': 'Blake', 'rank': 230, 'team': 'LAL', 'active': 1, 'position': ['PG']},
    {'first_name': 'Delonte', 'last_name': 'West', 'rank': 231, 'team': 'Bos', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'Kyle', 'last_name': 'Korver', 'rank': 232, 'team': 'Chi', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Jordan', 'last_name': 'Farmar', 'rank': 233, 'team': 'NJ', 'active': 1, 'position': ['PG']},
    {'first_name': 'Earl', 'last_name': 'Watson', 'rank': 234, 'team': 'Uta', 'active': 1, 'position': ['PG']},
    {'first_name': 'Ben', 'last_name': 'Wallace', 'rank': 235, 'team': 'Det', 'active': 1, 'position': ['C']},
    {'first_name': 'Peja', 'last_name': 'Stojakovic', 'rank': 236, 'team': 'Nor', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jose', 'last_name': 'Juan', 'rank': 237, 'team': 'Dal', 'active': 1, 'position': ['PG']},
    {'first_name': 'Chuck', 'last_name': 'Hayes', 'rank': 238, 'team': 'Hou', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Mario', 'last_name': 'Chalmers', 'rank': 239, 'team': 'Mia', 'active': 1, 'position': ['PG']},
    {'first_name': 'Donte', 'last_name': 'Greene', 'rank': 240, 'team': 'Sac', 'active': 1, 'position': ['SF']},
    {'first_name': 'Ronny', 'last_name': 'Turiaf', 'rank': 241, 'team': 'NY', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Joel', 'last_name': 'Przybilla', 'rank': 242, 'team': 'Por', 'active': 1, 'position': ['C']},
    {'first_name': 'Joel', 'last_name': 'Anthony', 'rank': 243, 'team': 'Mia', 'active': 1, 'position': ['C']},
    {'first_name': 'Will', 'last_name': 'Bynum', 'rank': 244, 'team': 'Det', 'active': 1, 'position': ['PG']},
    {'first_name': 'Nick', 'last_name': 'Young', 'rank': 245, 'team': 'Was', 'active': 1, 'position': ['SG']},
    {'first_name': 'Hasheem', 'last_name': 'Thabeet', 'rank': 246, 'team': 'Mem', 'active': 1, 'position': ['C']},
    {'first_name': 'Maurice', 'last_name': 'Evans', 'rank': 247, 'team': 'Atl', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Craig', 'last_name': 'Smith', 'rank': 248, 'team': 'LAC', 'active': 1, 'position': ['PF']},
    {'first_name': 'Tony', 'last_name': 'Allen', 'rank': 249, 'team': 'Mem', 'active': 1, 'position': ['SG']},
    {'first_name': 'Nenad', 'last_name': 'Krstic', 'rank': 250, 'team': 'OKC', 'active': 1, 'position': ['C']},
    {'first_name': 'David', 'last_name': 'Andersen', 'rank': 251, 'team': 'Tor', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Jason', 'last_name': 'Maxiell', 'rank': 252, 'team': 'Det', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Dahntay', 'last_name': 'Jones', 'rank': 253, 'team': 'Ind', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Chris', 'last_name': 'Duhon', 'rank': 254, 'team': 'Orl', 'active': 1, 'position': ['PG']},
    {'first_name': 'Tyler', 'last_name': 'Hansbrough', 'rank': 255, 'team': 'Ind', 'active': 1, 'position': ['PF']},
    {'first_name': 'Brandon', 'last_name': 'Bass', 'rank': 256, 'team': 'Orl', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jerryd', 'last_name': 'Bayless', 'rank': 257, 'team': 'Por', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Gordon', 'last_name': 'Hayward', 'rank': 258, 'team': 'Uta', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Austin', 'last_name': 'Daye', 'rank': 259, 'team': 'Det', 'active': 1, 'position': ['SF']},
    {'first_name': 'Shannon', 'last_name': 'Brown', 'rank': 260, 'team': 'LAL', 'active': 1, 'position': ['SG']},
    {'first_name': 'Eric', 'last_name': 'Maynor', 'rank': 261, 'team': 'OKC', 'active': 1, 'position': ['PG']},
    {'first_name': 'Ryan', 'last_name': 'Anderson', 'rank': 262, 'team': 'Orl', 'active': 1, 'position': ['PF']},
    {'first_name': 'Kendrick', 'last_name': 'Perkins', 'rank': 263, 'team': 'Bos', 'active': 1, 'position': ['C']},
    {'first_name': 'Jordan', 'last_name': 'Hill', 'rank': 264, 'team': 'Hou', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Nazr', 'last_name': 'Mohammed', 'rank': 265, 'team': 'Cha', 'active': 1, 'position': ['C']},
    {'first_name': 'Jeff', 'last_name': 'Teague', 'rank': 266, 'team': 'Atl', 'active': 1, 'position': ['PG']},
    {'first_name': 'Antonio', 'last_name': 'McDyess', 'rank': 267, 'team': 'SA', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Cole', 'last_name': 'Aldrich', 'rank': 268, 'team': 'OKC', 'active': 1, 'position': ['C']},
    {'first_name': 'Dominique', 'last_name': 'Jones', 'rank': 269, 'team': 'Dal', 'active': 1, 'position': ['SG']},
    {'first_name': 'Willie', 'last_name': 'Green', 'rank': 270, 'team': 'Nor', 'active': 1, 'position': ['SG']},
    {'first_name': 'Marcin', 'last_name': 'Gortat', 'rank': 271, 'team': 'Orl', 'active': 1, 'position': ['C']},
    {'first_name': 'Larry', 'last_name': 'Hughes', 'rank': 272, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Landry', 'last_name': 'Fields', 'rank': 273, 'team': 'NY', 'active': 1, 'position': ['SG']},
    {'first_name': 'Louis', 'last_name': 'Amundson', 'rank': 274, 'team': 'GS', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Xavier', 'last_name': 'Henry', 'rank': 275, 'team': 'Mem', 'active': 1, 'position': ['SG']},
    {'first_name': 'Sam', 'last_name': 'Young', 'rank': 276, 'team': 'Mem', 'active': 1, 'position': ['SF']},
    {'first_name': 'DeMarre', 'last_name': 'Carroll', 'rank': 277, 'team': 'Mem', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jodie', 'last_name': 'Meeks', 'rank': 278, 'team': 'Phi', 'active': 1, 'position': ['SG']},
    {'first_name': 'James', 'last_name': 'Singleton', 'rank': 279, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Kosta', 'last_name': 'Koufos', 'rank': 280, 'team': 'Min', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Daniel', 'last_name': 'Gibson', 'rank': 281, 'team': 'Cle', 'active': 1, 'position': ['PG']},
    {'first_name': 'Carlos', 'last_name': 'Arroyo', 'rank': 282, 'team': 'Mia', 'active': 1, 'position': ['PG']},
    {'first_name': 'Zaza', 'last_name': 'Pachulia', 'rank': 283, 'team': 'Atl', 'active': 1, 'position': ['C']},
    {'first_name': 'Joey', 'last_name': 'Dorsey', 'rank': 284, 'team': 'Tor', 'active': 1, 'position': ['PF']},
    {'first_name': 'Vladimir', 'last_name': 'Radmanovic', 'rank': 285, 'team': 'GS', 'active': 1, 'position': ['SF']},
    {'first_name': 'Charlie', 'last_name': 'Bell', 'rank': 286, 'team': 'GS', 'active': 1, 'position': ['SG']},
    {'first_name': 'James', 'last_name': 'Johnson', 'rank': 287, 'team': 'Chi', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Tim', 'last_name': 'Thomas', 'rank': 288, 'team': 'Dal', 'active': 1, 'position': ['PF']},
    {'first_name': 'Chris', 'last_name': 'Douglas-Roberts', 'rank': 289, 'team': 'Mil', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Darrell', 'last_name': 'Arthur', 'rank': 290, 'team': 'Mem', 'active': 1, 'position': ['PF']},
    {'first_name': 'Dominic', 'last_name': 'McGuire', 'rank': 291, 'team': 'Cha', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'DeAndre', 'last_name': 'Jordan', 'rank': 292, 'team': 'LAC', 'active': 1, 'position': ['C']},
    {'first_name': 'Kris', 'last_name': 'Humphries', 'rank': 293, 'team': 'NJ', 'active': 1, 'position': ['PF']},
    {'first_name': 'Matt', 'last_name': 'Bonner', 'rank': 294, 'team': 'SA', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Marquis', 'last_name': 'Daniels', 'rank': 295, 'team': 'Bos', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Kyle', 'last_name': 'Weaver', 'rank': 296, 'team': 'Chi', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Greivis', 'last_name': 'Vasquez', 'rank': 297, 'team': 'Mem', 'active': 1, 'position': ['PG']},
    {'first_name': 'Chris', 'last_name': 'Wilcox', 'rank': 298, 'team': 'Det', 'active': 1, 'position': ['PF']},
    {'first_name': 'Eric', 'last_name': 'Bledsoe', 'rank': 299, 'team': 'LAC', 'active': 1, 'position': ['PG']},
    {'first_name': 'Ronnie', 'last_name': 'Price', 'rank': 300, 'team': 'Uta', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jeff', 'last_name': 'Foster', 'rank': 301, 'team': 'Ind', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Wayne', 'last_name': 'Ellington', 'rank': 302, 'team': 'Min', 'active': 1, 'position': ['SG']},
    {'first_name': 'Larry', 'last_name': 'Sanders', 'rank': 303, 'team': 'Mil', 'active': 1, 'position': ['PF']},
    {'first_name': 'Lance', 'last_name': 'Stephenson', 'rank': 304, 'team': 'Ind', 'active': 1, 'position': ['SG']},
    {'first_name': 'Ekpe', 'last_name': 'Udoh', 'rank': 305, 'team': 'GS', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jannero', 'last_name': 'Pargo', 'rank': 306, 'team': 'Nor', 'active': 1, 'position': ['PG']},
    {'first_name': 'Patrick', 'last_name': 'Patterson', 'rank': 307, 'team': 'Hou', 'active': 1, 'position': ['PF']},
    {'first_name': 'B.J.', 'last_name': 'Mullens', 'rank': 308, 'team': 'OKC', 'active': 1, 'position': ['C']},
    {'first_name': 'Devin', 'last_name': 'Ebanks', 'rank': 309, 'team': 'LAL', 'active': 1, 'position': ['SF']},
    {'first_name': 'Joe', 'last_name': 'Alexander', 'rank': 310, 'team': 'Nor', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Josh', 'last_name': 'McRoberts', 'rank': 311, 'team': 'Ind', 'active': 1, 'position': ['PF']},
    {'first_name': 'Tony', 'last_name': 'Battie', 'rank': 312, 'team': 'Phi', 'active': 1, 'position': ['C']},
    {'first_name': 'Solomon', 'last_name': 'Jones', 'rank': 313, 'team': 'Ind', 'active': 1, 'position': ['C']},
    {'first_name': 'Leon', 'last_name': 'Powe', 'rank': 314, 'team': 'Cle', 'active': 1, 'position': ['PF']},
    {'first_name': 'Etan', 'last_name': 'Thomas', 'rank': 315, 'team': 'Atl', 'active': 1, 'position': ['C']},
    {'first_name': 'Derrick', 'last_name': 'Caracter', 'rank': 316, 'team': 'LAL', 'active': 1, 'position': ['PF']},
    {'first_name': 'Sean', 'last_name': 'Williams', 'rank': 317, 'team': 'FA', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Dan', 'last_name': 'Gadzuric', 'rank': 318, 'team': 'GS', 'active': 1, 'position': ['C']},
    {'first_name': 'Earl', 'last_name': 'Clark', 'rank': 319, 'team': 'Pho', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Gerald', 'last_name': 'Henderson', 'rank': 320, 'team': 'Cha', 'active': 1, 'position': ['SG']},
    {'first_name': 'Paul', 'last_name': 'George', 'rank': 321, 'team': 'Ind', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Kwame', 'last_name': 'Brown', 'rank': 322, 'team': 'Cha', 'active': 1, 'position': ['C']},
    {'first_name': 'Armon', 'last_name': 'Johnson', 'rank': 323, 'team': 'Por', 'active': 1, 'position': ['PG']},
    {'first_name': 'Elliot', 'last_name': 'Williams', 'rank': 324, 'team': 'Por', 'active': 1, 'position': ['SG']},
    {'first_name': 'Ryan', 'last_name': 'Hollins', 'rank': 325, 'team': 'Cle', 'active': 1, 'position': ['C']},
    {'first_name': 'Acie', 'last_name': 'Law', 'rank': 326, 'team': 'Mem', 'active': 1, 'position': ['PG']},
    {'first_name': 'Adam', 'last_name': 'Morrison', 'rank': 327, 'team': 'Was', 'active': 1, 'position': ['SF']},
    {'first_name': 'Anthony', 'last_name': 'Carter', 'rank': 328, 'team': 'Den', 'active': 1, 'position': ['PG']},
    {'first_name': 'Hamed', 'last_name': 'Haddadi', 'rank': 329, 'team': 'Mem', 'active': 1, 'position': ['C']},
    {'first_name': 'DaJuan', 'last_name': 'Summers', 'rank': 330, 'team': 'Det', 'active': 1, 'position': ['SF']},
    {'first_name': 'Luke', 'last_name': 'Harangody', 'rank': 331, 'team': 'Bos', 'active': 1, 'position': ['PF']},
    {'first_name': 'Lazar', 'last_name': 'Hayward', 'rank': 332, 'team': 'Min', 'active': 1, 'position': ['SF']},
    {'first_name': 'Christian', 'last_name': 'Eyenga', 'rank': 333, 'team': 'Cle', 'active': 1, 'position': ['SG']},
    {'first_name': 'Anthony', 'last_name': 'Roberson', 'rank': 334, 'team': 'LAC', 'active': 1, 'position': ['PG']},
    {'first_name': 'James', 'last_name': 'Anderson', 'rank': 335, 'team': 'SA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Will', 'last_name': 'Solomon', 'rank': 336, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Damion', 'last_name': 'James', 'rank': 337, 'team': 'NJ', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Alando', 'last_name': 'Tucker', 'rank': 338, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jawad', 'last_name': 'Williams', 'rank': 339, 'team': 'Cle', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Earl', 'last_name': 'Barron', 'rank': 340, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Luke', 'last_name': 'Walton', 'rank': 341, 'team': 'LAL', 'active': 1, 'position': ['SF']},
    {'first_name': 'Rodney', 'last_name': 'Carney', 'rank': 342, 'team': 'GS', 'active': 1, 'position': ['SF']},
    {'first_name': 'Alex', 'last_name': 'Acker', 'rank': 343, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Mardy', 'last_name': 'Collins', 'rank': 344, 'team': 'LAC', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'DeMarcus', 'last_name': 'Nelson', 'rank': 345, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Daequan', 'last_name': 'Cook', 'rank': 346, 'team': 'OKC', 'active': 1, 'position': ['SG']},
    {'first_name': 'Dexter', 'last_name': 'Pittman', 'rank': 347, 'team': 'Mia', 'active': 1, 'position': ['C']},
    {'first_name': "Da'Sean", 'last_name': 'Butler', 'rank': 348, 'team': 'Mia', 'active': 1, 'position': ['SF']},
    {'first_name': 'Trevor', 'last_name': 'Booker', 'rank': 349, 'team': 'Was', 'active': 1, 'position': ['PF']},
    {'first_name': 'Sonny', 'last_name': 'Weems', 'rank': 350, 'team': 'Tor', 'active': 1, 'position': ['SG']},
    {'first_name': 'Hilton', 'last_name': 'Armstrong', 'rank': 351, 'team': 'Was', 'active': 1, 'position': ['C']},
    {'first_name': 'DeShawn', 'last_name': 'Stevenson', 'rank': 352, 'team': 'Dal', 'active': 1, 'position': ['SG']},
    {'first_name': 'Ronald', 'last_name': 'Murray', 'rank': 353, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Stanley', 'last_name': 'Robinson', 'rank': 354, 'team': 'Orl', 'active': 1, 'position': ['SF']},
    {'first_name': 'Andy', 'last_name': 'Rautins', 'rank': 355, 'team': 'NY', 'active': 1, 'position': ['SG']},
    {'first_name': 'Morris', 'last_name': 'Peterson', 'rank': 356, 'team': 'OKC', 'active': 1, 'position': ['SG']},
    {'first_name': 'Jared', 'last_name': 'Jeffries', 'rank': 357, 'team': 'Hou', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Keyon', 'last_name': 'Dooling', 'rank': 358, 'team': 'Mil', 'active': 1, 'position': ['PG']},
    {'first_name': 'Francisco', 'last_name': 'Elson', 'rank': 359, 'team': 'Uta', 'active': 1, 'position': ['C']},
    {'first_name': 'Darnell', 'last_name': 'Jackson', 'rank': 360, 'team': 'Sac', 'active': 1, 'position': ['PF']},
    {'first_name': 'Darius', 'last_name': 'Songaila', 'rank': 361, 'team': 'Phi', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Dee', 'last_name': 'Brown', 'rank': 362, 'team': 'Dal', 'active': 1, 'position': ['PG']},
    {'first_name': 'Malik', 'last_name': 'Allen', 'rank': 363, 'team': 'Orl', 'active': 1, 'position': ['PF']},
    {'first_name': 'Rafer', 'last_name': 'Alston', 'rank': 364, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Derek', 'last_name': 'Anderson', 'rank': 365, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'A.J.', 'last_name': 'Price', 'rank': 366, 'team': 'Ind', 'active': 1, 'position': ['PG']},
    {'first_name': 'Darrell', 'last_name': 'Armstrong', 'rank': 367, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Chucky', 'last_name': 'Atkins', 'rank': 368, 'team': 'Pho', 'active': 1, 'position': ['PG']},
    {'first_name': 'Brent', 'last_name': 'Barry', 'rank': 369, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Maceo', 'last_name': 'Baston', 'rank': 370, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Mark', 'last_name': 'Blount', 'rank': 371, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Jason', 'last_name': 'Kapono', 'rank': 372, 'team': 'Phi', 'active': 1, 'position': ['SF']},
    {'first_name': 'Calvin', 'last_name': 'Booth', 'rank': 373, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Quinton', 'last_name': 'Ross', 'rank': 374, 'team': 'NJ', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Eddy', 'last_name': 'Curry', 'rank': 375, 'team': 'NY', 'active': 1, 'position': ['C']},
    {'first_name': 'Sebastian', 'last_name': 'Telfair', 'rank': 376, 'team': 'Min', 'active': 1, 'position': ['PG']},
    {'first_name': 'Bruce', 'last_name': 'Bowen', 'rank': 377, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Keith', 'last_name': 'Bogans', 'rank': 378, 'team': 'Chi', 'active': 1, 'position': ['SG']},
    {'first_name': 'Ryan', 'last_name': 'Bowen', 'rank': 379, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Earl', 'last_name': 'Boykins', 'rank': 380, 'team': 'Mil', 'active': 1, 'position': ['PG']},
    {'first_name': 'Primoz', 'last_name': 'Brezec', 'rank': 381, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'P.J.', 'last_name': 'Brown', 'rank': 382, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Greg', 'last_name': 'Buckner', 'rank': 383, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Brian', 'last_name': 'Cardinal', 'rank': 384, 'team': 'Dal', 'active': 1, 'position': ['PF']},
    {'first_name': 'Kareem', 'last_name': 'Rush', 'rank': 385, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Sam', 'last_name': 'Cassell', 'rank': 386, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Austin', 'last_name': 'Croshere', 'rank': 387, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jordan', 'last_name': 'Crawford', 'rank': 388, 'team': 'Atl', 'active': 1, 'position': ['SG']},
    {'first_name': 'Antonio', 'last_name': 'Daniels', 'rank': 389, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Ricky', 'last_name': 'Davis', 'rank': 390, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jon', 'last_name': 'Brockman', 'rank': 391, 'team': 'Mil', 'active': 1, 'position': ['PF']},
    {'first_name': 'Kaniel', 'last_name': 'Dickens', 'rank': 392, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Michael', 'last_name': 'Finley', 'rank': 393, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Dante', 'last_name': 'Cunningham', 'rank': 394, 'team': 'Por', 'active': 1, 'position': ['PF']},
    {'first_name': 'Adonal', 'last_name': 'Foyle', 'rank': 395, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Steve', 'last_name': 'Francis', 'rank': 396, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Pat', 'last_name': 'Garrity', 'rank': 397, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Devean', 'last_name': 'George', 'rank': 398, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Hassan', 'last_name': 'Whiteside', 'rank': 399, 'team': 'Sac', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Eddie', 'last_name': 'Gill', 'rank': 400, 'team': 'NJ', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jarvis', 'last_name': 'Varnado', 'rank': 401, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Quincy', 'last_name': 'Pondexter', 'rank': 402, 'team': 'Nor', 'active': 1, 'position': ['SF']},
    {'first_name': 'Craig', 'last_name': 'Brackins', 'rank': 403, 'team': 'Phi', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Terrico', 'last_name': 'White', 'rank': 404, 'team': 'Det', 'active': 1, 'position': ['SG']},
    {'first_name': 'Luke', 'last_name': 'Babbitt', 'rank': 405, 'team': 'Por', 'active': 1, 'position': ['SF']},
    {'first_name': 'Daniel', 'last_name': 'Orton', 'rank': 406, 'team': 'Orl', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Gordan', 'last_name': 'Giricek', 'rank': 407, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Jerome', 'last_name': 'Jordan', 'rank': 408, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Matt', 'last_name': 'Harpring', 'rank': 409, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Othella', 'last_name': 'Harrington', 'rank': 410, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jason', 'last_name': 'Hart', 'rank': 411, 'team': 'Min', 'active': 1, 'position': ['PG']},
    {'first_name': 'Solomon', 'last_name': 'Alabi', 'rank': 412, 'team': 'Tor', 'active': 1, 'position': ['C']},
    {'first_name': 'Patrick', 'last_name': 'Beverley', 'rank': 413, 'team': 'Mia', 'active': 1, 'position': ['PG']},
    {'first_name': 'Sundiata', 'last_name': 'Gaines', 'rank': 414, 'team': 'Uta', 'active': 1, 'position': ['PG']},
    {'first_name': 'Avery', 'last_name': 'Bradley', 'rank': 415, 'team': 'Bos', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'Tiny', 'last_name': 'Gallon', 'rank': 416, 'team': 'Mil', 'active': 1, 'position': ['PF']},
    {'first_name': 'Eddie', 'last_name': 'House', 'rank': 417, 'team': 'Mia', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Darington', 'last_name': 'Hobson', 'rank': 418, 'team': 'Mil', 'active': 1, 'position': ['SF']},
    {'first_name': 'Juwan', 'last_name': 'Howard', 'rank': 419, 'team': 'Mia', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Oliver', 'last_name': 'Lafayette', 'rank': 420, 'team': 'Bos', 'active': 1, 'position': ['SG']},
    {'first_name': 'Kenny', 'last_name': 'Hasbrouck', 'rank': 421, 'team': 'Mia', 'active': 1, 'position': ['SG']},
    {'first_name': 'Kevin', 'last_name': 'Seraphin', 'rank': 422, 'team': 'Was', 'active': 1, 'position': ['PF']},
    {'first_name': 'Troy', 'last_name': 'Hudson', 'rank': 423, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Lindsey', 'last_name': 'Hunter', 'rank': 424, 'team': 'FA', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Allen', 'last_name': 'Iverson', 'rank': 425, 'team': 'FA', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'Bobby', 'last_name': 'Jackson', 'rank': 426, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jerome', 'last_name': 'James', 'rank': 427, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Magnum', 'last_name': 'Rolle', 'rank': 428, 'team': 'Ind', 'active': 1, 'position': ['PF']},
    {'first_name': 'Marko', 'last_name': 'Jaric', 'rank': 429, 'team': 'FA', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'Luther', 'last_name': 'Head', 'rank': 430, 'team': 'Sac', 'active': 1, 'position': ['SG']},
    {'first_name': 'Ben', 'last_name': 'Uzoh', 'rank': 431, 'team': 'NJ', 'active': 1, 'position': ['SG']},
    {'first_name': 'Anthony', 'last_name': 'Johnson', 'rank': 432, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Latavious', 'last_name': 'Williams', 'rank': 433, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'DerMarr', 'last_name': 'Johnson', 'rank': 434, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Eddie', 'last_name': 'Jones', 'rank': 435, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Damon', 'last_name': 'Jones', 'rank': 436, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Darius', 'last_name': 'Miles', 'rank': 437, 'team': 'Cha', 'active': 1, 'position': ['SF']},
    {'first_name': 'Brevin', 'last_name': 'Knight', 'rank': 438, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Marcus', 'last_name': 'Williams', 'rank': 439, 'team': 'FA', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Tyronn', 'last_name': 'Lue', 'rank': 440, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Mark', 'last_name': 'Madsen', 'rank': 441, 'team': 'FA', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Jeremy', 'last_name': 'Evans', 'rank': 442, 'team': 'Uta', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jamaal', 'last_name': 'Magloire', 'rank': 443, 'team': 'Mia', 'active': 1, 'position': ['C']},
    {'first_name': 'Stephon', 'last_name': 'Marbury', 'rank': 444, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Sean', 'last_name': 'Marks', 'rank': 445, 'team': 'Was', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Donyell', 'last_name': 'Marshall', 'rank': 446, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Darrick', 'last_name': 'Martin', 'rank': 447, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Desmond', 'last_name': 'Mason', 'rank': 448, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jelani', 'last_name': 'McCoy', 'rank': 449, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Jeff', 'last_name': 'McInnis', 'rank': 450, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Eugene', 'last_name': 'Jeter', 'rank': 451, 'team': 'Sac', 'active': 1, 'position': ['PG']},
    {'first_name': 'Gani', 'last_name': 'Lawal', 'rank': 452, 'team': 'Pho', 'active': 1, 'position': ['PF']},
    {'first_name': 'Timofey', 'last_name': 'Mozgov', 'rank': 453, 'team': 'NY', 'active': 1, 'position': ['C']},
    {'first_name': 'Chris', 'last_name': 'Mihm', 'rank': 454, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Cuttino', 'last_name': 'Mobley', 'rank': 455, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Mikki', 'last_name': 'Moore', 'rank': 456, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Jeremy', 'last_name': 'Lin', 'rank': 457, 'team': 'GS', 'active': 1, 'position': ['PG']},
    {'first_name': 'Dikembe', 'last_name': 'Mutombo', 'rank': 458, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Matt', 'last_name': 'Janning', 'rank': 459, 'team': 'Pho', 'active': 1, 'position': ['SG']},
    {'first_name': 'Gary', 'last_name': 'Neal', 'rank': 460, 'team': 'SA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Sherron', 'last_name': 'Collins', 'rank': 461, 'team': 'Cha', 'active': 1, 'position': ['PG']},
    {'first_name': 'Donald', 'last_name': 'Sloan', 'rank': 462, 'team': 'Sac', 'active': 1, 'position': ['PG']},
    {'first_name': 'Samardo', 'last_name': 'Samuels', 'rank': 463, 'team': 'Cle', 'active': 1, 'position': ['PF']},
    {'first_name': 'Eduardo', 'last_name': 'Najera', 'rank': 464, 'team': 'Cha', 'active': 1, 'position': ['PF']},
    {'first_name': 'Rasho', 'last_name': 'Nesterovic', 'rank': 465, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Ira', 'last_name': 'Newble', 'rank': 466, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Kevin', 'last_name': 'Ollie', 'rank': 467, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Mike', 'last_name': 'Taylor', 'rank': 468, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Kyrylo', 'last_name': 'Fesenko', 'rank': 469, 'team': 'Uta', 'active': 1, 'position': ['C']},
    {'first_name': 'Bo', 'last_name': 'Outlaw', 'rank': 470, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Othyus', 'last_name': 'Jeffers', 'rank': 471, 'team': 'Uta', 'active': 1, 'position': ['SF']},
    {'first_name': 'Ruben', 'last_name': 'Patterson', 'rank': 472, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Eric', 'last_name': 'Piatkowski', 'rank': 473, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Scot', 'last_name': 'Pollard', 'rank': 474, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Theo', 'last_name': 'Ratliff', 'rank': 475, 'team': 'LAL', 'active': 1, 'position': ['C']},
    {'first_name': 'Malik', 'last_name': 'Rose', 'rank': 476, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Lester', 'last_name': 'Hudson', 'rank': 477, 'team': 'Was', 'active': 1, 'position': ['SG']},
    {'first_name': 'Michael', 'last_name': 'Ruffin', 'rank': 478, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Brian', 'last_name': 'Skinner', 'rank': 479, 'team': 'Mil', 'active': 1, 'position': ['C']},
    {'first_name': 'Joe', 'last_name': 'Smith', 'rank': 480, 'team': 'NJ', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jerry', 'last_name': 'Stackhouse', 'rank': 481, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Damon', 'last_name': 'Stoudamire', 'rank': 482, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Stromile', 'last_name': 'Swift', 'rank': 483, 'team': 'FA', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Wally', 'last_name': 'Szczerbiak', 'rank': 484, 'team': 'FA', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Kurt', 'last_name': 'Thomas', 'rank': 485, 'team': 'Chi', 'active': 1, 'position': ['PF']},
    {'first_name': 'Kenny', 'last_name': 'Thomas', 'rank': 486, 'team': 'Mem', 'active': 1, 'position': ['PF']},
    {'first_name': 'Ime', 'last_name': 'Udoka', 'rank': 487, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jacque', 'last_name': 'Vaughn', 'rank': 488, 'team': 'SA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jake', 'last_name': 'Voskuhl', 'rank': 489, 'team': 'LAC', 'active': 1, 'position': ['C']},
    {'first_name': 'Antoine', 'last_name': 'Walker', 'rank': 490, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Rasheed', 'last_name': 'Wallace', 'rank': 491, 'team': 'FA', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Aaron', 'last_name': 'Williams', 'rank': 492, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Jason', 'last_name': 'Collins', 'rank': 493, 'team': 'Atl', 'active': 1, 'position': ['C']},
    {'first_name': 'Jarron', 'last_name': 'Collins', 'rank': 494, 'team': 'LAC', 'active': 1, 'position': ['C']},
    {'first_name': 'DeSagana', 'last_name': 'Diop', 'rank': 495, 'team': 'Cha', 'active': 1, 'position': ['C']},
    {'first_name': 'Trenton', 'last_name': 'Hassell', 'rank': 496, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Steven', 'last_name': 'Hunter', 'rank': 497, 'team': 'FA', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Brian', 'last_name': 'Scalabrine', 'rank': 498, 'team': 'Chi', 'active': 1, 'position': ['PF']},
    {'first_name': 'Bobby', 'last_name': 'Simmons', 'rank': 499, 'team': 'SA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jamaal', 'last_name': 'Tinsley', 'rank': 500, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Loren', 'last_name': 'Woods', 'rank': 501, 'team': 'Cle', 'active': 1, 'position': ['C']},
    {'first_name': 'Mike', 'last_name': 'James', 'rank': 502, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Dan', 'last_name': 'Dickau', 'rank': 503, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Juan', 'last_name': 'Dixon', 'rank': 504, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Melvin', 'last_name': 'Ely', 'rank': 505, 'team': 'Den', 'active': 1, 'position': ['C']},
    {'first_name': 'Casey', 'last_name': 'Jacobsen', 'rank': 506, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Fred', 'last_name': 'Jones', 'rank': 507, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Bostjan', 'last_name': 'Nachbar', 'rank': 508, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Juan', 'last_name': 'Carlos', 'rank': 509, 'team': 'FA', 'active': 1, 'position': ['SG', 'PG']},
    {'first_name': 'Smush', 'last_name': 'Parker', 'rank': 510, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Reggie', 'last_name': 'Evans', 'rank': 511, 'team': 'Tor', 'active': 1, 'position': ['PF']},
    {'first_name': 'Devin', 'last_name': 'Brown', 'rank': 512, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Richie', 'last_name': 'Frahm', 'rank': 513, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Mike', 'last_name': 'Wilks', 'rank': 514, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jarvis', 'last_name': 'Hayes', 'rank': 515, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Brian', 'last_name': 'Cook', 'rank': 516, 'team': 'LAC', 'active': 1, 'position': ['PF']},
    {'first_name': 'James', 'last_name': 'Jones', 'rank': 517, 'team': 'Mia', 'active': 1, 'position': ['SF']},
    {'first_name': 'Marcus', 'last_name': 'Banks', 'rank': 518, 'team': 'Tor', 'active': 1, 'position': ['PG']},
    {'first_name': 'Sasha', 'last_name': 'Pavlovic', 'rank': 519, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Josh', 'last_name': 'Powell', 'rank': 520, 'team': 'Atl', 'active': 1, 'position': ['PF']},
    {'first_name': 'Matt', 'last_name': 'Carroll', 'rank': 521, 'team': 'Cha', 'active': 1, 'position': ['SG']},
    {'first_name': 'Ronald', 'last_name': 'Dupree', 'rank': 522, 'team': 'Tor', 'active': 1, 'position': ['SF']},
    {'first_name': 'Linton', 'last_name': 'Johnson', 'rank': 523, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'David', 'last_name': 'Harrison', 'rank': 524, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Royal', 'last_name': 'Ivey', 'rank': 525, 'team': 'OKC', 'active': 1, 'position': ['PG']},
    {'first_name': 'Robert', 'last_name': 'Swift', 'rank': 526, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Sasha', 'last_name': 'Vujacic', 'rank': 527, 'team': 'LAL', 'active': 1, 'position': ['SG']},
    {'first_name': 'Viktor', 'last_name': 'Khryapa', 'rank': 528, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Kirk', 'last_name': 'Snyder', 'rank': 529, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'D.J.', 'last_name': 'Mbenga', 'rank': 530, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Billy', 'last_name': 'Thomas', 'rank': 531, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Damien', 'last_name': 'Wilkins', 'rank': 532, 'team': 'Mem', 'active': 1, 'position': ['SG']},
    {'first_name': 'Andre', 'last_name': 'Barrett', 'rank': 533, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Andre', 'last_name': 'Brown', 'rank': 534, 'team': 'Mia', 'active': 1, 'position': ['PF']},
    {'first_name': 'Awvee', 'last_name': 'Storey', 'rank': 535, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Adrian', 'last_name': 'Griffin', 'rank': 536, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Kasib', 'last_name': 'Powell', 'rank': 537, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Travis', 'last_name': 'Diener', 'rank': 538, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Ike', 'last_name': 'Diogu', 'rank': 539, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Mickael', 'last_name': 'Gelabale', 'rank': 540, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Joey', 'last_name': 'Graham', 'rank': 541, 'team': 'Cle', 'active': 1, 'position': ['SF']},
    {'first_name': 'Gerald', 'last_name': 'Green', 'rank': 542, 'team': 'FA', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Orien', 'last_name': 'Greene', 'rank': 543, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Ian', 'last_name': 'Mahinmi', 'rank': 544, 'team': 'Dal', 'active': 1, 'position': ['C']},
    {'first_name': 'Rashad', 'last_name': 'McCants', 'rank': 545, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Johan', 'last_name': 'Petro', 'rank': 546, 'team': 'NJ', 'active': 1, 'position': ['C']},
    {'first_name': 'Salim', 'last_name': 'Stoudamire', 'rank': 547, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Von', 'last_name': 'Wafer', 'rank': 548, 'team': 'Bos', 'active': 1, 'position': ['SG']},
    {'first_name': 'Antoine', 'last_name': 'Wright', 'rank': 549, 'team': 'Sac', 'active': 1, 'position': ['SG']},
    {'first_name': 'Fabricio', 'last_name': 'Oberto', 'rank': 550, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Shavlik', 'last_name': 'Randolph', 'rank': 551, 'team': 'Mia', 'active': 1, 'position': ['C']},
    {'first_name': 'Dwayne', 'last_name': 'Jones', 'rank': 552, 'team': 'Pho', 'active': 1, 'position': ['C']},
    {'first_name': 'Stephen', 'last_name': 'Graham', 'rank': 553, 'team': 'NJ', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Keith', 'last_name': 'Langford', 'rank': 554, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Andre', 'last_name': 'Owens', 'rank': 555, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Maurice', 'last_name': 'Ager', 'rank': 556, 'team': 'Min', 'active': 1, 'position': ['SG']},
    {'first_name': 'James', 'last_name': 'Augustine', 'rank': 557, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Renaldo', 'last_name': 'Balkman', 'rank': 558, 'team': 'Den', 'active': 1, 'position': ['SF']},
    {'first_name': 'Josh', 'last_name': 'Boone', 'rank': 559, 'team': 'FA', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Cheikh', 'last_name': 'Samb', 'rank': 560, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Paul', 'last_name': 'Davis', 'rank': 561, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Guillermo', 'last_name': 'Diaz', 'rank': 562, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Quincy', 'last_name': 'Douby', 'rank': 563, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Alexander', 'last_name': 'Johnson', 'rank': 564, 'team': 'Hou', 'active': 1, 'position': ['PF']},
    {'first_name': 'Bobby', 'last_name': 'Jones', 'rank': 565, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Steve', 'last_name': 'Novak', 'rank': 566, 'team': 'Dal', 'active': 1, 'position': ['PF']},
    {'first_name': 'Patrick', 'last_name': "O'Bryant", 'rank': 567, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Oleksiy', 'last_name': 'Pecherov', 'rank': 568, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Kosta', 'last_name': 'Perovic', 'rank': 569, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Sergio', 'last_name': 'Rodriguez', 'rank': 570, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Mouhamed', 'last_name': 'Sene', 'rank': 571, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Cedric', 'last_name': 'Simmons', 'rank': 572, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Marcus', 'last_name': 'Vinicius', 'rank': 573, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Shawne', 'last_name': 'Williams', 'rank': 574, 'team': 'NY', 'active': 1, 'position': ['SF']},
    {'first_name': 'Marcus', 'last_name': 'Williams', 'rank': 575, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Shelden', 'last_name': 'Williams', 'rank': 576, 'team': 'Den', 'active': 1, 'position': ['PF']},
    {'first_name': 'Tarence', 'last_name': 'Kinsey', 'rank': 577, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Chris', 'last_name': 'Quinn', 'rank': 578, 'team': 'Phi', 'active': 1, 'position': ['PG']},
    {'first_name': 'Yakhouba', 'last_name': 'Diawara', 'rank': 579, 'team': 'FA', 'active': 1, 'position': ['SG', 'SF']},
    {'first_name': 'Jorge', 'last_name': 'Garbajosa', 'rank': 580, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Justin', 'last_name': 'Williams', 'rank': 581, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Darius', 'last_name': 'Washington', 'rank': 582, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Walter', 'last_name': 'Herrmann', 'rank': 583, 'team': 'FA', 'active': 1, 'position': ['SF', 'PF']},
    {'first_name': 'Mike', 'last_name': 'Harris', 'rank': 584, 'team': 'Hou', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jeremy', 'last_name': 'Richardson', 'rank': 585, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Randolph', 'last_name': 'Morris', 'rank': 586, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Morris', 'last_name': 'Almond', 'rank': 587, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Marco', 'last_name': 'Belinelli', 'rank': 588, 'team': 'Nor', 'active': 1, 'position': ['SG']},
    {'first_name': 'Javaris', 'last_name': 'Crittenton', 'rank': 589, 'team': 'Cha', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jermareo', 'last_name': 'Davidson', 'rank': 590, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Nick', 'last_name': 'Fazekas', 'rank': 591, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Aaron', 'last_name': 'Gray', 'rank': 592, 'team': 'Nor', 'active': 1, 'position': ['C']},
    {'first_name': 'Taurean', 'last_name': 'Green', 'rank': 593, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Stephane', 'last_name': 'Lasme', 'rank': 594, 'team': 'Bos', 'active': 1, 'position': ['PF']},
    {'first_name': 'Demetris', 'last_name': 'Nichols', 'rank': 595, 'team': 'Uta', 'active': 1, 'position': ['SF']},
    {'first_name': 'Michael', 'last_name': 'Doleac', 'rank': 596, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Gabe', 'last_name': 'Pruitt', 'rank': 597, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Chris', 'last_name': 'Richard', 'rank': 598, 'team': 'Chi', 'active': 1, 'position': ['C']},
    {'first_name': 'Jason', 'last_name': 'Smith', 'rank': 599, 'team': 'Nor', 'active': 1, 'position': ['PF']},
    {'first_name': 'D.J.', 'last_name': 'Strawberry', 'rank': 600, 'team': 'Nor', 'active': 1, 'position': ['SG']},
    {'first_name': 'Coby', 'last_name': 'Karl', 'rank': 601, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Thomas', 'last_name': 'Gardner', 'rank': 602, 'team': 'Mem', 'active': 1, 'position': ['SG']},
    {'first_name': 'Courtney', 'last_name': 'Sims', 'rank': 603, 'team': 'Den', 'active': 1, 'position': ['C']},
    {'first_name': 'Mario', 'last_name': 'West', 'rank': 604, 'team': 'Bos', 'active': 1, 'position': ['SG']},
    {'first_name': 'Darryl', 'last_name': 'Watkins', 'rank': 605, 'team': 'Nor', 'active': 1, 'position': ['C']},
    {'first_name': 'Lance', 'last_name': 'Allred', 'rank': 606, 'team': 'Ind', 'active': 1, 'position': ['C']},
    {'first_name': 'Blake', 'last_name': 'Ahearn', 'rank': 607, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Speedy', 'last_name': 'Claxton', 'rank': 608, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Keith', 'last_name': 'McLeod', 'rank': 609, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Sean', 'last_name': 'May', 'rank': 610, 'team': 'FA', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Hassan', 'last_name': 'Adams', 'rank': 611, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Herbert', 'last_name': 'Hill', 'rank': 612, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Alexis', 'last_name': 'Ajinca', 'rank': 613, 'team': 'Dal', 'active': 1, 'position': ['C']},
    {'first_name': 'Omer', 'last_name': 'Asik', 'rank': 614, 'team': 'Chi', 'active': 1, 'position': ['C']},
    {'first_name': 'Joe', 'last_name': 'Crawford', 'rank': 615, 'team': 'Sac', 'active': 1, 'position': ['SG']},
    {'first_name': 'Tadija', 'last_name': 'Dragicevic', 'rank': 616, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Semih', 'last_name': 'Erden', 'rank': 617, 'team': 'Bos', 'active': 1, 'position': ['C']},
    {'first_name': 'Patrick', 'last_name': 'Ewing', 'rank': 618, 'team': 'NY', 'active': 1, 'position': ['SF']},
    {'first_name': 'Shan', 'last_name': 'Foster', 'rank': 619, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'J.R.', 'last_name': 'Giddens', 'rank': 620, 'team': 'Sac', 'active': 1, 'position': ['SG']},
    {'first_name': 'James', 'last_name': 'Gist', 'rank': 621, 'team': 'SA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Malik', 'last_name': 'Hairston', 'rank': 622, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'DeVon', 'last_name': 'Hardin', 'rank': 623, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Richard', 'last_name': 'Hendrix', 'rank': 624, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Nathan', 'last_name': 'Jawai', 'rank': 625, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Maarty', 'last_name': 'Leunen', 'rank': 626, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Nikola', 'last_name': 'Pekovic', 'rank': 627, 'team': 'Min', 'active': 1, 'position': ['C']},
    {'first_name': 'Trent', 'last_name': 'Plaisted', 'rank': 628, 'team': 'Phi', 'active': 1, 'position': ['PF']},
    {'first_name': 'Walter', 'last_name': 'Sharpe', 'rank': 629, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Sean', 'last_name': 'Singletary', 'rank': 630, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Ante', 'last_name': 'Tomic', 'rank': 631, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Deron', 'last_name': 'Washington', 'rank': 632, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'D.J.', 'last_name': 'White', 'rank': 633, 'team': 'OKC', 'active': 1, 'position': ['PF']},
    {'first_name': 'David', 'last_name': 'Padgett', 'rank': 634, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jason', 'last_name': 'Richards', 'rank': 635, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Dwayne', 'last_name': 'Mitchell', 'rank': 636, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Sun', 'last_name': 'Yue', 'rank': 637, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Othello', 'last_name': 'Hunter', 'rank': 638, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Sasha', 'last_name': 'Kaun', 'rank': 639, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Jamaal', 'last_name': 'Tatum', 'rank': 640, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Dion', 'last_name': 'Dowell', 'rank': 641, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Steven', 'last_name': 'Hill', 'rank': 642, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Brandon', 'last_name': 'Heath', 'rank': 643, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'C.J.', 'last_name': 'Giles', 'rank': 644, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Desmon', 'last_name': 'Farmer', 'rank': 645, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Devin', 'last_name': 'Green', 'rank': 646, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Taj', 'last_name': 'McCullough', 'rank': 647, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Justin', 'last_name': 'Reed', 'rank': 648, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Andre', 'last_name': 'Emmett', 'rank': 649, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Rob', 'last_name': 'Kurz', 'rank': 650, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Bobby', 'last_name': 'Brown', 'rank': 651, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jared', 'last_name': 'Reiner', 'rank': 652, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Antywane', 'last_name': 'Robinson', 'rank': 653, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Dan', 'last_name': 'Grunfeld', 'rank': 654, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Maureece', 'last_name': 'Rice', 'rank': 655, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Eddie', 'last_name': 'Basden', 'rank': 656, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Matt', 'last_name': 'Walsh', 'rank': 657, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Roger', 'last_name': 'Powell', 'rank': 658, 'team': 'Chi', 'active': 1, 'position': ['SF']},
    {'first_name': 'Robert', 'last_name': 'Hite', 'rank': 659, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Elton', 'last_name': 'Brown', 'rank': 660, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Dontell', 'last_name': 'Jefferson', 'rank': 661, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Trey', 'last_name': 'Johnson', 'rank': 662, 'team': 'LAL', 'active': 1, 'position': ['SG']},
    {'first_name': 'Omar', 'last_name': 'Barlett', 'rank': 663, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Coleman', 'last_name': 'Collins', 'rank': 664, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Tre', 'last_name': 'Kelley', 'rank': 665, 'team': 'Mem', 'active': 1, 'position': ['SG']},
    {'first_name': 'Curtis', 'last_name': 'Sumpter', 'rank': 666, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Julius', 'last_name': 'Hodge', 'rank': 667, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Donell', 'last_name': 'Taylor', 'rank': 668, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'David', 'last_name': 'Noel', 'rank': 669, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jared', 'last_name': 'Jordan', 'rank': 670, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Marcus', 'last_name': 'Campbell', 'rank': 671, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Brent', 'last_name': 'Petway', 'rank': 672, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Brian', 'last_name': 'Hamilton', 'rank': 673, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Cory', 'last_name': 'Underwood', 'rank': 674, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jamal', 'last_name': 'Sampson', 'rank': 675, 'team': 'FA', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'Raef', 'last_name': 'LaFrentz', 'rank': 676, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Malick', 'last_name': 'Badiane', 'rank': 677, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Reyshawn', 'last_name': 'Terry', 'rank': 678, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'James', 'last_name': 'Mays', 'rank': 679, 'team': 'GS', 'active': 1, 'position': ['PF']},
    {'first_name': 'Brian', 'last_name': 'Morrison', 'rank': 680, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Charles', 'last_name': 'Rhodes', 'rank': 681, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'JaJuan', 'last_name': 'Smith', 'rank': 682, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Olumide', 'last_name': 'Oyedeji', 'rank': 683, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Josh', 'last_name': 'Davis', 'rank': 684, 'team': 'Mem', 'active': 1, 'position': ['PF']},
    {'first_name': 'Noel', 'last_name': 'Felix', 'rank': 685, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Cheyne', 'last_name': 'Gadson', 'rank': 686, 'team': 'GS', 'active': 1, 'position': ['SG']},
    {'first_name': 'Charles', 'last_name': 'Gaines', 'rank': 687, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Marcus', 'last_name': 'Hubbard', 'rank': 688, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Frank', 'last_name': 'Robinson', 'rank': 689, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Gabe', 'last_name': 'Muoneke', 'rank': 690, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Derrick', 'last_name': 'Byars', 'rank': 691, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Kevin', 'last_name': 'Kruger', 'rank': 692, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Vernon', 'last_name': 'Hamilton', 'rank': 693, 'team': 'Det', 'active': 1, 'position': ['SG']},
    {'first_name': 'T.J.', 'last_name': 'Cummings', 'rank': 694, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Cartier', 'last_name': 'Martin', 'rank': 695, 'team': 'Was', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Pops', 'last_name': 'Mensah-Bonsu', 'rank': 696, 'team': 'Nor', 'active': 1, 'position': ['PF', 'C']},
    {'first_name': 'James', 'last_name': 'White', 'rank': 697, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Chris', 'last_name': 'Hunter', 'rank': 698, 'team': 'FA', 'active': 1, 'position': ['C', 'PF']},
    {'first_name': 'Marcus', 'last_name': 'Haislip', 'rank': 699, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Derrick', 'last_name': 'Brown', 'rank': 700, 'team': 'Cha', 'active': 1, 'position': ['PF']},
    {'first_name': 'Taylor', 'last_name': 'Griffin', 'rank': 701, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Jermaine', 'last_name': 'Taylor', 'rank': 702, 'team': 'Hou', 'active': 1, 'position': ['SG']},
    {'first_name': 'Daniel', 'last_name': 'Green', 'rank': 703, 'team': 'Cle', 'active': 1, 'position': ['SF']},
    {'first_name': 'Trey', 'last_name': 'Gilder', 'rank': 704, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Warren', 'last_name': 'Carter', 'rank': 705, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Jeff', 'last_name': 'Pendergraph', 'rank': 706, 'team': 'Por', 'active': 1, 'position': ['PF']},
    {'first_name': 'Garrett', 'last_name': 'Temple', 'rank': 707, 'team': 'SA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Will', 'last_name': 'Conroy', 'rank': 708, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Marcus', 'last_name': 'Landry', 'rank': 709, 'team': 'Sac', 'active': 1, 'position': ['SF']},
    {'first_name': 'Vincent', 'last_name': 'Grier', 'rank': 710, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Lawrence', 'last_name': 'Roberts', 'rank': 711, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Rod', 'last_name': 'Benson', 'rank': 712, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Brandon', 'last_name': 'Bowman', 'rank': 713, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Dionte', 'last_name': 'Christmas', 'rank': 714, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Leon', 'last_name': 'Rodgers', 'rank': 715, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Aaron', 'last_name': 'Miles', 'rank': 716, 'team': 'GS', 'active': 1, 'position': ['PG']},
    {'first_name': 'Spencer', 'last_name': 'Nelson', 'rank': 717, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Carlos', 'last_name': 'Powell', 'rank': 718, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Antonio', 'last_name': 'Anderson', 'rank': 719, 'team': 'Hou', 'active': 1, 'position': ['SG']},
    {'first_name': 'Michael', 'last_name': 'Fey', 'rank': 720, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Tony', 'last_name': 'Gaffney', 'rank': 721, 'team': 'Bos', 'active': 1, 'position': ['SG']},
    {'first_name': 'Paul', 'last_name': 'Harris', 'rank': 722, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Thomas', 'last_name': 'Kelati', 'rank': 723, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Bonzi', 'last_name': 'Wells', 'rank': 724, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'David', 'last_name': 'Monds', 'rank': 725, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Shaun', 'last_name': 'Pruitt', 'rank': 726, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Garret', 'last_name': 'Siler', 'rank': 727, 'team': 'Pho', 'active': 1, 'position': ['C']},
    {'first_name': 'Lanny', 'last_name': 'Smith', 'rank': 728, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Will', 'last_name': 'Blalock', 'rank': 729, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Mustafa', 'last_name': 'Shakur', 'rank': 730, 'team': 'Nor', 'active': 1, 'position': ['PG']},
    {'first_name': 'Michael', 'last_name': 'Sweetney', 'rank': 731, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Curtis', 'last_name': 'Jerrells', 'rank': 732, 'team': 'SA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Luke', 'last_name': 'Jackson', 'rank': 733, 'team': 'Mem', 'active': 1, 'position': ['SF', 'SG']},
    {'first_name': 'Goran', 'last_name': 'Suton', 'rank': 734, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Nick', 'last_name': 'Calathes', 'rank': 735, 'team': 'FA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Victor', 'last_name': 'Claver', 'rank': 736, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Ricky', 'last_name': 'Rubio', 'rank': 737, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Patrick', 'last_name': 'Mills', 'rank': 738, 'team': 'Por', 'active': 1, 'position': ['PG']},
    {'first_name': 'Jonathan', 'last_name': 'Bender', 'rank': 739, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Alonzo', 'last_name': 'Gee', 'rank': 740, 'team': 'SA', 'active': 1, 'position': ['SG']},
    {'first_name': 'Brian', 'last_name': 'Butch', 'rank': 741, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Roko', 'last_name': 'Ukic', 'rank': 742, 'team': 'FA', 'active': 1, 'position': ['PG', 'SG']},
    {'first_name': 'Greg', 'last_name': 'Stiemsma', 'rank': 743, 'team': 'Min', 'active': 1, 'position': ['C']},
    {'first_name': 'Nemanja', 'last_name': 'Bjelica', 'rank': 744, 'team': 'FA', 'active': 1, 'position': ['SF']},
    {'first_name': 'Dwayne', 'last_name': 'Collins', 'rank': 745, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Hamady', 'last_name': 'Ndiaye', 'rank': 746, 'team': 'Was', 'active': 1, 'position': ['C']},
    {'first_name': 'Gerry', 'last_name': 'McNamara', 'rank': 747, 'team': 'FA', 'active': 1, 'position': ['PG']},
    {'first_name': 'Pape', 'last_name': 'Sy', 'rank': 748, 'team': 'Atl', 'active': 1, 'position': ['PF']},
    {'first_name': 'Chris', 'last_name': 'Alexander', 'rank': 749, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Willie', 'last_name': 'Warren', 'rank': 750, 'team': 'LAC', 'active': 1, 'position': ['SG']},
    {'first_name': 'Ryan', 'last_name': 'Richards', 'rank': 751, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Matt', 'last_name': 'Freije', 'rank': 752, 'team': 'FA', 'active': 1, 'position': ['PF', 'SF']},
    {'first_name': 'Brian', 'last_name': 'Zoubek', 'rank': 753, 'team': 'NJ', 'active': 1, 'position': ['C']},
    {'first_name': 'Paulo', 'last_name': 'Prestes', 'rank': 754, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Ryan', 'last_name': 'Reid', 'rank': 755, 'team': 'FA', 'active': 1, 'position': ['PF']},
    {'first_name': 'Zhang', 'last_name': 'Kai', 'rank': 756, 'team': 'FA', 'active': 1, 'position': ['C']},
    {'first_name': 'Tibor', 'last_name': 'Pleiss', 'rank': 757, 'team': 'FA', 'active': 1, 'position': ['C']}
];

setTimeout(function(){
    db.populate('nba_players', nba_players, function(err,docs){
        console.log('Cleared and added ' + docs.length + ' NBA players');
    });
}, 2000);
